// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"hash/maphash"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectJoins = getJoins[*dialect.SelectQuery]()
	UpdateJoins = getJoins[*dialect.UpdateQuery]()
	DeleteJoins = getJoins[*dialect.DeleteQuery]()
)

type joinSet[Q interface{ aliasedAs(string) Q }] struct {
	InnerJoin Q
	LeftJoin  Q
	RightJoin Q
}

func (j joinSet[Q]) AliasedAs(alias string) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: j.InnerJoin.aliasedAs(alias),
		LeftJoin:  j.LeftJoin.aliasedAs(alias),
		RightJoin: j.RightJoin.aliasedAs(alias),
	}
}

type joins[Q dialect.Joinable] struct {
	Events       joinSet[eventJoins[Q]]
	PointSystems joinSet[pointSystemJoins[Q]]
	RacingSims   joinSet[racingSimJoins[Q]]
	Seasons      joinSet[seasonJoins[Q]]
	Serieses     joinSet[seriesJoins[Q]]
	Teams        joinSet[teamJoins[Q]]
}

func buildJoinSet[Q interface{ aliasedAs(string) Q }, C any, F func(C, string) Q](c C, f F) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: f(c, clause.InnerJoin),
		LeftJoin:  f(c, clause.LeftJoin),
		RightJoin: f(c, clause.RightJoin),
	}
}

func getJoins[Q dialect.Joinable]() joins[Q] {
	return joins[Q]{
		Events:       buildJoinSet[eventJoins[Q]](Events.Columns, buildEventJoins),
		PointSystems: buildJoinSet[pointSystemJoins[Q]](PointSystems.Columns, buildPointSystemJoins),
		RacingSims:   buildJoinSet[racingSimJoins[Q]](RacingSims.Columns, buildRacingSimJoins),
		Seasons:      buildJoinSet[seasonJoins[Q]](Seasons.Columns, buildSeasonJoins),
		Serieses:     buildJoinSet[seriesJoins[Q]](Serieses.Columns, buildSeriesJoins),
		Teams:        buildJoinSet[teamJoins[Q]](Teams.Columns, buildTeamJoins),
	}
}

type modAs[Q any, C interface{ AliasedAs(string) C }] struct {
	c C
	f func(C) bob.Mod[Q]
}

func (m modAs[Q, C]) Apply(q Q) {
	m.f(m.c).Apply(q)
}

func (m modAs[Q, C]) AliasedAs(alias string) bob.Mod[Q] {
	m.c = m.c.AliasedAs(alias)
	return m
}

func randInt() int64 {
	out := int64(new(maphash.Hash).Sum64())

	if out < 0 {
		return -out % 10000
	}

	return out % 10000
}
