// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	Drivers      driverWhere[Q]
	Events       eventWhere[Q]
	PointSystems pointSystemWhere[Q]
	RacingSims   racingSimWhere[Q]
	Seasons      seasonWhere[Q]
	Serieses     seriesWhere[Q]
	Teams        teamWhere[Q]
} {
	return struct {
		Drivers      driverWhere[Q]
		Events       eventWhere[Q]
		PointSystems pointSystemWhere[Q]
		RacingSims   racingSimWhere[Q]
		Seasons      seasonWhere[Q]
		Serieses     seriesWhere[Q]
		Teams        teamWhere[Q]
	}{
		Drivers:      buildDriverWhere[Q](Drivers.Columns),
		Events:       buildEventWhere[Q](Events.Columns),
		PointSystems: buildPointSystemWhere[Q](PointSystems.Columns),
		RacingSims:   buildRacingSimWhere[Q](RacingSims.Columns),
		Seasons:      buildSeasonWhere[Q](Seasons.Columns),
		Serieses:     buildSeriesWhere[Q](Serieses.Columns),
		Teams:        buildTeamWhere[Q](Teams.Columns),
	}
}
