// Code generated by BobGen psql v0.48.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// PointSystem is an object representing the database table.
type PointSystem struct {
	ID              int32            `db:"id,pk" `
	Name            string           `db:"name" `
	Description     null.Val[string] `db:"description" `
	IsActive        bool             `db:"is_active" `
	GuestPoints     bool             `db:"guest_points" `
	RaceDistancePCT decimal.Decimal  `db:"race_distance_pct" `
	CreatedAt       time.Time        `db:"created_at" `
	UpdatedAt       time.Time        `db:"updated_at" `
	CreatedBy       string           `db:"created_by" `
	UpdatedBy       string           `db:"updated_by" `

	R pointSystemR `db:"-" `

	C pointSystemC `db:"-" `
}

// PointSystemSlice is an alias for a slice of pointers to PointSystem.
// This should almost always be used instead of []*PointSystem.
type PointSystemSlice []*PointSystem

// PointSystems contains methods to work with the point_systems table
var PointSystems = psql.NewTablex[*PointSystem, PointSystemSlice, *PointSystemSetter]("", "point_systems", buildPointSystemColumns("point_systems"))

// PointSystemsQuery is a query on the point_systems table
type PointSystemsQuery = *psql.ViewQuery[*PointSystem, PointSystemSlice]

// pointSystemR is where relationships are stored.
type pointSystemR struct {
	PointRules PointRuleSlice // point_rules.point_rules_point_system_id_fk
	Seasons    SeasonSlice    // seasons.seasons_point_system_id_fk
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded pointSystemRLoaded `db:"-" `
}

// pointSystemRLoaded tracks which relationships on PointSystem have been loaded.
type pointSystemRLoaded struct {
	PointRules bool // point_rules.point_rules_point_system_id_fk
	Seasons    bool // seasons.seasons_point_system_id_fk
}

func buildPointSystemColumns(tableName string) pointSystemColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "description", "is_active", "guest_points", "race_distance_pct", "created_at", "updated_at", "created_by", "updated_by",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return pointSystemColumns{
		ColumnsExpr:     columnsExpr,
		tableAlias:      tableName,
		ID:              buildPointSystemColumn(tableName, "id"),
		Name:            buildPointSystemColumn(tableName, "name"),
		Description:     buildPointSystemColumn(tableName, "description"),
		IsActive:        buildPointSystemColumn(tableName, "is_active"),
		GuestPoints:     buildPointSystemColumn(tableName, "guest_points"),
		RaceDistancePCT: buildPointSystemColumn(tableName, "race_distance_pct"),
		CreatedAt:       buildPointSystemColumn(tableName, "created_at"),
		UpdatedAt:       buildPointSystemColumn(tableName, "updated_at"),
		CreatedBy:       buildPointSystemColumn(tableName, "created_by"),
		UpdatedBy:       buildPointSystemColumn(tableName, "updated_by"),
	}
}

type pointSystemColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              pointSystemColumn
	Name            pointSystemColumn
	Description     pointSystemColumn
	IsActive        pointSystemColumn
	GuestPoints     pointSystemColumn
	RaceDistancePCT pointSystemColumn
	CreatedAt       pointSystemColumn
	UpdatedAt       pointSystemColumn
	CreatedBy       pointSystemColumn
	UpdatedBy       pointSystemColumn
}

// Alias returns the current table alias for the columns set.
func (c pointSystemColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (pointSystemColumns) AliasedAs(tableName string) pointSystemColumns {
	return buildPointSystemColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c pointSystemColumns) Unqualified() pointSystemColumns {
	return buildPointSystemColumns("")
}

func buildPointSystemColumn(alias, name string) pointSystemColumn {
	return pointSystemColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type pointSystemColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c pointSystemColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c pointSystemColumn) ShouldOmitParens() bool {
	return true
}

// PointSystemSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PointSystemSetter struct {
	ID              omit.Val[int32]           `db:"id,pk" `
	Name            omit.Val[string]          `db:"name" `
	Description     omitnull.Val[string]      `db:"description" `
	IsActive        omit.Val[bool]            `db:"is_active" `
	GuestPoints     omit.Val[bool]            `db:"guest_points" `
	RaceDistancePCT omit.Val[decimal.Decimal] `db:"race_distance_pct" `
	CreatedAt       omit.Val[time.Time]       `db:"created_at" `
	UpdatedAt       omit.Val[time.Time]       `db:"updated_at" `
	CreatedBy       omit.Val[string]          `db:"created_by" `
	UpdatedBy       omit.Val[string]          `db:"updated_by" `
}

func (s PointSystemSetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Description.IsValue() || s.Description.IsNull() {
		vals = append(vals, "description")
	}
	if s.IsActive.IsValue() {
		vals = append(vals, "is_active")
	}
	if s.GuestPoints.IsValue() {
		vals = append(vals, "guest_points")
	}
	if s.RaceDistancePCT.IsValue() {
		vals = append(vals, "race_distance_pct")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if s.CreatedBy.IsValue() {
		vals = append(vals, "created_by")
	}
	if s.UpdatedBy.IsValue() {
		vals = append(vals, "updated_by")
	}
	return vals
}

func (s PointSystemSetter) Overwrite(t *PointSystem) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Description.IsValue() || s.Description.IsNull() {
		t.Description = s.Description.MustGetNull()
	}
	if s.IsActive.IsValue() {
		t.IsActive = s.IsActive.MustGet()
	}
	if s.GuestPoints.IsValue() {
		t.GuestPoints = s.GuestPoints.MustGet()
	}
	if s.RaceDistancePCT.IsValue() {
		t.RaceDistancePCT = s.RaceDistancePCT.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if s.CreatedBy.IsValue() {
		t.CreatedBy = s.CreatedBy.MustGet()
	}
	if s.UpdatedBy.IsValue() {
		t.UpdatedBy = s.UpdatedBy.MustGet()
	}
}

func (s *PointSystemSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PointSystems.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Name.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Description.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Description.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.IsActive.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.IsActive.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.GuestPoints.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.GuestPoints.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.RaceDistancePCT.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.RaceDistancePCT.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.UpdatedAt.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedBy.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.CreatedBy.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.UpdatedBy.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.UpdatedBy.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s PointSystemSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PointSystemSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Description.IsValue() || s.Description.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.IsActive.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if s.GuestPoints.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "guest_points")...),
			psql.Arg(s.GuestPoints),
		}})
	}

	if s.RaceDistancePCT.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "race_distance_pct")...),
			psql.Arg(s.RaceDistancePCT),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.CreatedBy.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_by")...),
			psql.Arg(s.CreatedBy),
		}})
	}

	if s.UpdatedBy.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_by")...),
			psql.Arg(s.UpdatedBy),
		}})
	}

	return exprs
}

// FindPointSystem retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPointSystem(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*PointSystem, error) {
	if len(cols) == 0 {
		return PointSystems.Query(
			sm.Where(PointSystems.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return PointSystems.Query(
		sm.Where(PointSystems.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(PointSystems.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PointSystemExists checks the presence of a single record by primary key
func PointSystemExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return PointSystems.Query(
		sm.Where(PointSystems.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PointSystem is retrieved from the database
func (o *PointSystem) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PointSystems.AfterSelectHooks.RunHooks(ctx, exec, PointSystemSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PointSystems.AfterInsertHooks.RunHooks(ctx, exec, PointSystemSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PointSystems.AfterUpdateHooks.RunHooks(ctx, exec, PointSystemSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PointSystems.AfterDeleteHooks.RunHooks(ctx, exec, PointSystemSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = PointSystems.AfterMergeHooks.RunHooks(ctx, exec, PointSystemSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the PointSystem
func (o *PointSystem) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *PointSystem) pkEQ() dialect.Expression {
	return psql.Quote("point_systems", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PointSystem
func (o *PointSystem) Update(ctx context.Context, exec bob.Executor, s *PointSystemSetter) error {
	v, err := PointSystems.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single PointSystem record with an executor
func (o *PointSystem) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PointSystems.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PointSystem using the executor
func (o *PointSystem) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PointSystems.Query(
		sm.Where(PointSystems.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PointSystemSlice is retrieved from the database
func (o PointSystemSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PointSystems.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PointSystems.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PointSystems.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PointSystems.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = PointSystems.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PointSystemSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("point_systems", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PointSystemSlice) copyMatchingRows(from ...*PointSystem) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PointSystemSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PointSystems.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PointSystem:
				o.copyMatchingRows(retrieved)
			case []*PointSystem:
				o.copyMatchingRows(retrieved...)
			case PointSystemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PointSystem or a slice of PointSystem
				// then run the AfterUpdateHooks on the slice
				_, err = PointSystems.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PointSystemSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PointSystems.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PointSystem:
				o.copyMatchingRows(retrieved)
			case []*PointSystem:
				o.copyMatchingRows(retrieved...)
			case PointSystemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PointSystem or a slice of PointSystem
				// then run the AfterDeleteHooks on the slice
				_, err = PointSystems.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o PointSystemSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PointSystems.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PointSystem:
				o.copyMatchingRows(retrieved)
			case []*PointSystem:
				o.copyMatchingRows(retrieved...)
			case PointSystemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PointSystem or a slice of PointSystem
				// then run the AfterMergeHooks on the slice
				_, err = PointSystems.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o PointSystemSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PointSystemSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PointSystems.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PointSystemSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PointSystems.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PointSystemSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PointSystems.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// PointRules starts a query for related objects on point_rules
func (o *PointSystem) PointRules(mods ...bob.Mod[*dialect.SelectQuery]) PointRulesQuery {
	return PointRules.Query(append(mods,
		sm.Where(PointRules.Columns.PointSystemID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os PointSystemSlice) PointRules(mods ...bob.Mod[*dialect.SelectQuery]) PointRulesQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}

	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "integer[]"))

	return PointRules.Query(append(mods,
		sm.Where(PointRules.Columns.PointSystemID.EQ(PKArgExpr)),
	)...)
}

// Seasons starts a query for related objects on seasons
func (o *PointSystem) Seasons(mods ...bob.Mod[*dialect.SelectQuery]) SeasonsQuery {
	return Seasons.Query(append(mods,
		sm.Where(Seasons.Columns.PointSystemID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os PointSystemSlice) Seasons(mods ...bob.Mod[*dialect.SelectQuery]) SeasonsQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}

	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "integer[]"))

	return Seasons.Query(append(mods,
		sm.Where(Seasons.Columns.PointSystemID.EQ(PKArgExpr)),
	)...)
}

func insertPointSystemPointRules0(ctx context.Context, exec bob.Executor, pointRules1 []*PointRuleSetter, pointSystem0 *PointSystem) (PointRuleSlice, error) {
	for i := range pointRules1 {
		pointRules1[i].PointSystemID = omit.From(pointSystem0.ID)
	}

	ret, err := PointRules.Insert(bob.ToMods(pointRules1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertPointSystemPointRules0: %w", err)
	}

	return ret, nil
}

func attachPointSystemPointRules0(ctx context.Context, exec bob.Executor, count int, pointRules1 PointRuleSlice, pointSystem0 *PointSystem) (PointRuleSlice, error) {
	setter := &PointRuleSetter{
		PointSystemID: omit.From(pointSystem0.ID),
	}

	err := pointRules1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachPointSystemPointRules0: %w", err)
	}

	return pointRules1, nil
}

func (pointSystem0 *PointSystem) InsertPointRules(ctx context.Context, exec bob.Executor, related ...*PointRuleSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	pointRules1, err := insertPointSystemPointRules0(ctx, exec, related, pointSystem0)
	if err != nil {
		return err
	}

	pointSystem0.R.PointRules = append(pointSystem0.R.PointRules, pointRules1...)

	for _, rel := range pointRules1 {
		rel.R.PointSystem = pointSystem0
		rel.R.Loaded.PointSystem = true
	}
	return nil
}

func (pointSystem0 *PointSystem) AttachPointRules(ctx context.Context, exec bob.Executor, related ...*PointRule) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	pointRules1 := PointRuleSlice(related)

	_, err = attachPointSystemPointRules0(ctx, exec, len(related), pointRules1, pointSystem0)
	if err != nil {
		return err
	}

	pointSystem0.R.PointRules = append(pointSystem0.R.PointRules, pointRules1...)

	for _, rel := range related {
		rel.R.PointSystem = pointSystem0
		rel.R.Loaded.PointSystem = true
	}

	return nil
}

func insertPointSystemSeasons0(ctx context.Context, exec bob.Executor, seasons1 []*SeasonSetter, pointSystem0 *PointSystem) (SeasonSlice, error) {
	for i := range seasons1 {
		seasons1[i].PointSystemID = omit.From(pointSystem0.ID)
	}

	ret, err := Seasons.Insert(bob.ToMods(seasons1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertPointSystemSeasons0: %w", err)
	}

	return ret, nil
}

func attachPointSystemSeasons0(ctx context.Context, exec bob.Executor, count int, seasons1 SeasonSlice, pointSystem0 *PointSystem) (SeasonSlice, error) {
	setter := &SeasonSetter{
		PointSystemID: omit.From(pointSystem0.ID),
	}

	err := seasons1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachPointSystemSeasons0: %w", err)
	}

	return seasons1, nil
}

func (pointSystem0 *PointSystem) InsertSeasons(ctx context.Context, exec bob.Executor, related ...*SeasonSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	seasons1, err := insertPointSystemSeasons0(ctx, exec, related, pointSystem0)
	if err != nil {
		return err
	}

	pointSystem0.R.Seasons = append(pointSystem0.R.Seasons, seasons1...)

	for _, rel := range seasons1 {
		rel.R.PointSystem = pointSystem0
		rel.R.Loaded.PointSystem = true
	}
	return nil
}

func (pointSystem0 *PointSystem) AttachSeasons(ctx context.Context, exec bob.Executor, related ...*Season) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	seasons1 := SeasonSlice(related)

	_, err = attachPointSystemSeasons0(ctx, exec, len(related), seasons1, pointSystem0)
	if err != nil {
		return err
	}

	pointSystem0.R.Seasons = append(pointSystem0.R.Seasons, seasons1...)

	for _, rel := range related {
		rel.R.PointSystem = pointSystem0
		rel.R.Loaded.PointSystem = true
	}

	return nil
}

type pointSystemWhere[Q psql.Filterable] struct {
	ID              psql.WhereMod[Q, int32]
	Name            psql.WhereMod[Q, string]
	Description     psql.WhereNullMod[Q, string]
	IsActive        psql.WhereMod[Q, bool]
	GuestPoints     psql.WhereMod[Q, bool]
	RaceDistancePCT psql.WhereMod[Q, decimal.Decimal]
	CreatedAt       psql.WhereMod[Q, time.Time]
	UpdatedAt       psql.WhereMod[Q, time.Time]
	CreatedBy       psql.WhereMod[Q, string]
	UpdatedBy       psql.WhereMod[Q, string]
}

func (pointSystemWhere[Q]) AliasedAs(alias string) pointSystemWhere[Q] {
	return buildPointSystemWhere[Q](buildPointSystemColumns(alias))
}

func buildPointSystemWhere[Q psql.Filterable](cols pointSystemColumns) pointSystemWhere[Q] {
	return pointSystemWhere[Q]{
		ID:              psql.Where[Q, int32](cols.ID.Expression),
		Name:            psql.Where[Q, string](cols.Name.Expression),
		Description:     psql.WhereNull[Q, string](cols.Description.Expression),
		IsActive:        psql.Where[Q, bool](cols.IsActive.Expression),
		GuestPoints:     psql.Where[Q, bool](cols.GuestPoints.Expression),
		RaceDistancePCT: psql.Where[Q, decimal.Decimal](cols.RaceDistancePCT.Expression),
		CreatedAt:       psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:       psql.Where[Q, time.Time](cols.UpdatedAt.Expression),
		CreatedBy:       psql.Where[Q, string](cols.CreatedBy.Expression),
		UpdatedBy:       psql.Where[Q, string](cols.UpdatedBy.Expression),
	}
}

func (o *PointSystem) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PointRules":
		rels, ok := retrieved.(PointRuleSlice)
		if !ok {
			return fmt.Errorf("pointSystem cannot load %T as %q", retrieved, name)
		}

		o.R.PointRules = rels
		o.R.Loaded.PointRules = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.PointSystem = o
				rel.R.Loaded.PointSystem = true
			}
		}
		return nil
	case "Seasons":
		rels, ok := retrieved.(SeasonSlice)
		if !ok {
			return fmt.Errorf("pointSystem cannot load %T as %q", retrieved, name)
		}

		o.R.Seasons = rels
		o.R.Loaded.Seasons = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.PointSystem = o
				rel.R.Loaded.PointSystem = true
			}
		}
		return nil
	default:
		return fmt.Errorf("pointSystem has no relationship %q", name)
	}
}

type pointSystemPreloader struct{}

func buildPointSystemPreloader() pointSystemPreloader {
	return pointSystemPreloader{}
}

type pointSystemThenLoader[Q orm.Loadable] struct {
	PointRules func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Seasons    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPointSystemThenLoader[Q orm.Loadable]() pointSystemThenLoader[Q] {
	type PointRulesLoadInterface interface {
		LoadPointRules(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type SeasonsLoadInterface interface {
		LoadSeasons(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return pointSystemThenLoader[Q]{
		PointRules: thenLoadBuilder[Q](
			"PointRules",
			func(ctx context.Context, exec bob.Executor, retrieved PointRulesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPointRules(ctx, exec, mods...)
			},
		),
		Seasons: thenLoadBuilder[Q](
			"Seasons",
			func(ctx context.Context, exec bob.Executor, retrieved SeasonsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSeasons(ctx, exec, mods...)
			},
		),
	}
}

// LoadPointRules loads the pointSystem's PointRules into the .R struct
func (o *PointSystem) LoadPointRules(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PointRules = nil
	o.R.Loaded.PointRules = false

	related, err := o.PointRules(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.PointSystem = o
		rel.R.Loaded.PointSystem = true
	}

	o.R.PointRules = related
	o.R.Loaded.PointRules = true
	return nil
}

// LoadPointRules loads the pointSystem's PointRules into the .R struct
func (os PointSystemSlice) LoadPointRules(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	pointRules, err := os.PointRules(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.PointRules = nil
		o.R.Loaded.PointRules = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	pointSystemByKey := make(map[int32][]*PointSystem, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		pointSystemByKey[o.ID] = append(pointSystemByKey[o.ID], o)
	}

	for _, rel := range pointRules {

		owners, ok := pointSystemByKey[rel.PointSystemID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.PointSystem = o
			rel.R.Loaded.PointSystem = true

			o.R.PointRules = append(o.R.PointRules, rel)

		}
	}

	return nil
}

// LoadSeasons loads the pointSystem's Seasons into the .R struct
func (o *PointSystem) LoadSeasons(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Seasons = nil
	o.R.Loaded.Seasons = false

	related, err := o.Seasons(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.PointSystem = o
		rel.R.Loaded.PointSystem = true
	}

	o.R.Seasons = related
	o.R.Loaded.Seasons = true
	return nil
}

// LoadSeasons loads the pointSystem's Seasons into the .R struct
func (os PointSystemSlice) LoadSeasons(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	seasons, err := os.Seasons(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Seasons = nil
		o.R.Loaded.Seasons = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	pointSystemByKey := make(map[int32][]*PointSystem, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		pointSystemByKey[o.ID] = append(pointSystemByKey[o.ID], o)
	}

	for _, rel := range seasons {

		owners, ok := pointSystemByKey[rel.PointSystemID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.PointSystem = o
			rel.R.Loaded.PointSystem = true

			o.R.Seasons = append(o.R.Seasons, rel)

		}
	}

	return nil
}

// pointSystemC is where relationship counts are stored.
type pointSystemC struct {
	PointRules *int64
	Seasons    *int64
}

// PreloadCount sets a count in the C struct by name
func (o *PointSystem) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PointRules":
		o.C.PointRules = &count
	case "Seasons":
		o.C.Seasons = &count
	}
	return nil
}

type pointSystemCountPreloader struct {
	PointRules func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	Seasons    func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildPointSystemCountPreloader() pointSystemCountPreloader {
	return pointSystemCountPreloader{
		PointRules: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*PointSystem]("PointRules", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = PointSystems.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(PointRules.NameAsExpr()),
					sm.Where(psql.Quote(PointRules.Alias(), "point_system_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		Seasons: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*PointSystem]("Seasons", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = PointSystems.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Seasons.NameAsExpr()),
					sm.Where(psql.Quote(Seasons.Alias(), "point_system_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type pointSystemCountThenLoader[Q orm.Loadable] struct {
	PointRules func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Seasons    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPointSystemCountThenLoader[Q orm.Loadable]() pointSystemCountThenLoader[Q] {
	type PointRulesCountInterface interface {
		LoadCountPointRules(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type SeasonsCountInterface interface {
		LoadCountSeasons(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return pointSystemCountThenLoader[Q]{
		PointRules: countThenLoadBuilder[Q](
			"PointRules",
			func(ctx context.Context, exec bob.Executor, retrieved PointRulesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountPointRules(ctx, exec, mods...)
			},
		),
		Seasons: countThenLoadBuilder[Q](
			"Seasons",
			func(ctx context.Context, exec bob.Executor, retrieved SeasonsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountSeasons(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountPointRules loads the count of PointRules into the C struct
func (o *PointSystem) LoadCountPointRules(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.PointRules(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.PointRules = &count
	return nil
}

// LoadCountPointRules loads the count of PointRules for a slice in a single batch query
func (os PointSystemSlice) LoadCountPointRules(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "integer[]"))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			PointRules.Columns.PointSystemID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(PointRules.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(PointRules.Columns.PointSystemID.EQ(PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(PointRules.Columns.PointSystemID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.PointRules = &count
	}

	return nil
}

// LoadCountSeasons loads the count of Seasons into the C struct
func (o *PointSystem) LoadCountSeasons(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Seasons(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Seasons = &count
	return nil
}

// LoadCountSeasons loads the count of Seasons for a slice in a single batch query
func (os PointSystemSlice) LoadCountSeasons(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "integer[]"))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Seasons.Columns.PointSystemID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Seasons.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(Seasons.Columns.PointSystemID.EQ(PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Seasons.Columns.PointSystemID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Seasons = &count
	}

	return nil
}

type pointSystemJoins[Q dialect.Joinable] struct {
	typ        string
	PointRules modAs[Q, pointRuleColumns]
	Seasons    modAs[Q, seasonColumns]
}

func (j pointSystemJoins[Q]) aliasedAs(alias string) pointSystemJoins[Q] {
	return buildPointSystemJoins[Q](buildPointSystemColumns(alias), j.typ)
}

func buildPointSystemJoins[Q dialect.Joinable](cols pointSystemColumns, typ string) pointSystemJoins[Q] {
	return pointSystemJoins[Q]{
		typ: typ,
		PointRules: modAs[Q, pointRuleColumns]{
			c: PointRules.Columns,
			f: func(to pointRuleColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PointRules.NameExpr().As(to.Alias())).On(
						to.PointSystemID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Seasons: modAs[Q, seasonColumns]{
			c: Seasons.Columns,
			f: func(to seasonColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Seasons.NameExpr().As(to.Alias())).On(
						to.PointSystemID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
