// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// RacingSim is an object representing the database table.
type RacingSim struct {
	ID                     int32          `db:"id,pk" `
	FrontendID             uuid.UUID      `db:"frontend_id" `
	Name                   string         `db:"name" `
	SupportedImportFormats pq.StringArray `db:"supported_import_formats" `
	IsActive               bool           `db:"is_active" `
	CreatedAt              time.Time      `db:"created_at" `
	UpdatedAt              time.Time      `db:"updated_at" `
	CreatedBy              string         `db:"created_by" `
	UpdatedBy              string         `db:"updated_by" `

	R racingSimR `db:"-" `
}

// RacingSimSlice is an alias for a slice of pointers to RacingSim.
// This should almost always be used instead of []*RacingSim.
type RacingSimSlice []*RacingSim

// RacingSims contains methods to work with the racing_sims table
var RacingSims = psql.NewTablex[*RacingSim, RacingSimSlice, *RacingSimSetter]("", "racing_sims", buildRacingSimColumns("racing_sims"))

// RacingSimsQuery is a query on the racing_sims table
type RacingSimsQuery = *psql.ViewQuery[*RacingSim, RacingSimSlice]

// racingSimR is where relationships are stored.
type racingSimR struct {
	SimulationSeries                       SeriesSlice                     // series.series_simulation_id_fk
	SimulationSimulationCarAliases         SimulationCarAliasSlice         // simulation_car_aliases.simulation_car_aliases_simulation_id_fk
	SimulationSimulationDriverAliases      SimulationDriverAliasSlice      // simulation_driver_aliases.simulation_driver_aliases_simulation_id_fk
	SimulationSimulationTrackLayoutAliases SimulationTrackLayoutAliasSlice // simulation_track_layout_aliases.simulation_track_layout_aliases_simulation_id_fk
}

func buildRacingSimColumns(alias string) racingSimColumns {
	return racingSimColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "frontend_id", "name", "supported_import_formats", "is_active", "created_at", "updated_at", "created_by", "updated_by",
		).WithParent("racing_sims"),
		tableAlias:             alias,
		ID:                     psql.Quote(alias, "id"),
		FrontendID:             psql.Quote(alias, "frontend_id"),
		Name:                   psql.Quote(alias, "name"),
		SupportedImportFormats: psql.Quote(alias, "supported_import_formats"),
		IsActive:               psql.Quote(alias, "is_active"),
		CreatedAt:              psql.Quote(alias, "created_at"),
		UpdatedAt:              psql.Quote(alias, "updated_at"),
		CreatedBy:              psql.Quote(alias, "created_by"),
		UpdatedBy:              psql.Quote(alias, "updated_by"),
	}
}

type racingSimColumns struct {
	expr.ColumnsExpr
	tableAlias             string
	ID                     psql.Expression
	FrontendID             psql.Expression
	Name                   psql.Expression
	SupportedImportFormats psql.Expression
	IsActive               psql.Expression
	CreatedAt              psql.Expression
	UpdatedAt              psql.Expression
	CreatedBy              psql.Expression
	UpdatedBy              psql.Expression
}

func (c racingSimColumns) Alias() string {
	return c.tableAlias
}

func (racingSimColumns) AliasedAs(alias string) racingSimColumns {
	return buildRacingSimColumns(alias)
}

// RacingSimSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RacingSimSetter struct {
	ID                     omit.Val[int32]          `db:"id,pk" `
	FrontendID             omit.Val[uuid.UUID]      `db:"frontend_id" `
	Name                   omit.Val[string]         `db:"name" `
	SupportedImportFormats omit.Val[pq.StringArray] `db:"supported_import_formats" `
	IsActive               omit.Val[bool]           `db:"is_active" `
	CreatedAt              omit.Val[time.Time]      `db:"created_at" `
	UpdatedAt              omit.Val[time.Time]      `db:"updated_at" `
	CreatedBy              omit.Val[string]         `db:"created_by" `
	UpdatedBy              omit.Val[string]         `db:"updated_by" `
}

func (s RacingSimSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.FrontendID.IsValue() {
		vals = append(vals, "frontend_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.SupportedImportFormats.IsValue() {
		vals = append(vals, "supported_import_formats")
	}
	if s.IsActive.IsValue() {
		vals = append(vals, "is_active")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if s.CreatedBy.IsValue() {
		vals = append(vals, "created_by")
	}
	if s.UpdatedBy.IsValue() {
		vals = append(vals, "updated_by")
	}
	return vals
}

func (s RacingSimSetter) Overwrite(t *RacingSim) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.FrontendID.IsValue() {
		t.FrontendID = s.FrontendID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.SupportedImportFormats.IsValue() {
		t.SupportedImportFormats = s.SupportedImportFormats.MustGet()
	}
	if s.IsActive.IsValue() {
		t.IsActive = s.IsActive.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if s.CreatedBy.IsValue() {
		t.CreatedBy = s.CreatedBy.MustGet()
	}
	if s.UpdatedBy.IsValue() {
		t.UpdatedBy = s.UpdatedBy.MustGet()
	}
}

func (s *RacingSimSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RacingSims.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 9)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.FrontendID.IsValue() {
			vals[1] = psql.Arg(s.FrontendID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.SupportedImportFormats.IsValue() {
			vals[3] = psql.Arg(s.SupportedImportFormats.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.IsActive.IsValue() {
			vals[4] = psql.Arg(s.IsActive.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[5] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[6] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedBy.IsValue() {
			vals[7] = psql.Arg(s.CreatedBy.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.UpdatedBy.IsValue() {
			vals[8] = psql.Arg(s.UpdatedBy.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s RacingSimSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RacingSimSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.FrontendID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "frontend_id")...),
			psql.Arg(s.FrontendID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.SupportedImportFormats.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "supported_import_formats")...),
			psql.Arg(s.SupportedImportFormats),
		}})
	}

	if s.IsActive.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.CreatedBy.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_by")...),
			psql.Arg(s.CreatedBy),
		}})
	}

	if s.UpdatedBy.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_by")...),
			psql.Arg(s.UpdatedBy),
		}})
	}

	return exprs
}

// FindRacingSim retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRacingSim(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*RacingSim, error) {
	if len(cols) == 0 {
		return RacingSims.Query(
			sm.Where(RacingSims.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return RacingSims.Query(
		sm.Where(RacingSims.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(RacingSims.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RacingSimExists checks the presence of a single record by primary key
func RacingSimExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return RacingSims.Query(
		sm.Where(RacingSims.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RacingSim is retrieved from the database
func (o *RacingSim) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RacingSims.AfterSelectHooks.RunHooks(ctx, exec, RacingSimSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RacingSims.AfterInsertHooks.RunHooks(ctx, exec, RacingSimSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RacingSims.AfterUpdateHooks.RunHooks(ctx, exec, RacingSimSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RacingSims.AfterDeleteHooks.RunHooks(ctx, exec, RacingSimSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the RacingSim
func (o *RacingSim) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *RacingSim) pkEQ() dialect.Expression {
	return psql.Quote("racing_sims", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RacingSim
func (o *RacingSim) Update(ctx context.Context, exec bob.Executor, s *RacingSimSetter) error {
	v, err := RacingSims.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single RacingSim record with an executor
func (o *RacingSim) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RacingSims.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RacingSim using the executor
func (o *RacingSim) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RacingSims.Query(
		sm.Where(RacingSims.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after RacingSimSlice is retrieved from the database
func (o RacingSimSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RacingSims.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RacingSims.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RacingSims.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RacingSims.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o RacingSimSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("racing_sims", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RacingSimSlice) copyMatchingRows(from ...*RacingSim) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RacingSimSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RacingSims.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RacingSim:
				o.copyMatchingRows(retrieved)
			case []*RacingSim:
				o.copyMatchingRows(retrieved...)
			case RacingSimSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RacingSim or a slice of RacingSim
				// then run the AfterUpdateHooks on the slice
				_, err = RacingSims.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RacingSimSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RacingSims.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RacingSim:
				o.copyMatchingRows(retrieved)
			case []*RacingSim:
				o.copyMatchingRows(retrieved...)
			case RacingSimSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RacingSim or a slice of RacingSim
				// then run the AfterDeleteHooks on the slice
				_, err = RacingSims.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RacingSimSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RacingSimSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RacingSims.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RacingSimSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RacingSims.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RacingSimSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RacingSims.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// SimulationSeries starts a query for related objects on series
func (o *RacingSim) SimulationSeries(mods ...bob.Mod[*dialect.SelectQuery]) SeriesesQuery {
	return Serieses.Query(append(mods,
		sm.Where(Serieses.Columns.SimulationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os RacingSimSlice) SimulationSeries(mods ...bob.Mod[*dialect.SelectQuery]) SeriesesQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return Serieses.Query(append(mods,
		sm.Where(psql.Group(Serieses.Columns.SimulationID).OP("IN", PKArgExpr)),
	)...)
}

// SimulationSimulationCarAliases starts a query for related objects on simulation_car_aliases
func (o *RacingSim) SimulationSimulationCarAliases(mods ...bob.Mod[*dialect.SelectQuery]) SimulationCarAliasesQuery {
	return SimulationCarAliases.Query(append(mods,
		sm.Where(SimulationCarAliases.Columns.SimulationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os RacingSimSlice) SimulationSimulationCarAliases(mods ...bob.Mod[*dialect.SelectQuery]) SimulationCarAliasesQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return SimulationCarAliases.Query(append(mods,
		sm.Where(psql.Group(SimulationCarAliases.Columns.SimulationID).OP("IN", PKArgExpr)),
	)...)
}

// SimulationSimulationDriverAliases starts a query for related objects on simulation_driver_aliases
func (o *RacingSim) SimulationSimulationDriverAliases(mods ...bob.Mod[*dialect.SelectQuery]) SimulationDriverAliasesQuery {
	return SimulationDriverAliases.Query(append(mods,
		sm.Where(SimulationDriverAliases.Columns.SimulationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os RacingSimSlice) SimulationSimulationDriverAliases(mods ...bob.Mod[*dialect.SelectQuery]) SimulationDriverAliasesQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return SimulationDriverAliases.Query(append(mods,
		sm.Where(psql.Group(SimulationDriverAliases.Columns.SimulationID).OP("IN", PKArgExpr)),
	)...)
}

// SimulationSimulationTrackLayoutAliases starts a query for related objects on simulation_track_layout_aliases
func (o *RacingSim) SimulationSimulationTrackLayoutAliases(mods ...bob.Mod[*dialect.SelectQuery]) SimulationTrackLayoutAliasesQuery {
	return SimulationTrackLayoutAliases.Query(append(mods,
		sm.Where(SimulationTrackLayoutAliases.Columns.SimulationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os RacingSimSlice) SimulationSimulationTrackLayoutAliases(mods ...bob.Mod[*dialect.SelectQuery]) SimulationTrackLayoutAliasesQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return SimulationTrackLayoutAliases.Query(append(mods,
		sm.Where(psql.Group(SimulationTrackLayoutAliases.Columns.SimulationID).OP("IN", PKArgExpr)),
	)...)
}

func insertRacingSimSimulationSeries0(ctx context.Context, exec bob.Executor, serieses1 []*SeriesSetter, racingSim0 *RacingSim) (SeriesSlice, error) {
	for i := range serieses1 {
		serieses1[i].SimulationID = omit.From(racingSim0.ID)
	}

	ret, err := Serieses.Insert(bob.ToMods(serieses1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertRacingSimSimulationSeries0: %w", err)
	}

	return ret, nil
}

func attachRacingSimSimulationSeries0(ctx context.Context, exec bob.Executor, count int, serieses1 SeriesSlice, racingSim0 *RacingSim) (SeriesSlice, error) {
	setter := &SeriesSetter{
		SimulationID: omit.From(racingSim0.ID),
	}

	err := serieses1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachRacingSimSimulationSeries0: %w", err)
	}

	return serieses1, nil
}

func (racingSim0 *RacingSim) InsertSimulationSeries(ctx context.Context, exec bob.Executor, related ...*SeriesSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	serieses1, err := insertRacingSimSimulationSeries0(ctx, exec, related, racingSim0)
	if err != nil {
		return err
	}

	racingSim0.R.SimulationSeries = append(racingSim0.R.SimulationSeries, serieses1...)

	for _, rel := range serieses1 {
		rel.R.SimulationRacingSim = racingSim0
	}
	return nil
}

func (racingSim0 *RacingSim) AttachSimulationSeries(ctx context.Context, exec bob.Executor, related ...*Series) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	serieses1 := SeriesSlice(related)

	_, err = attachRacingSimSimulationSeries0(ctx, exec, len(related), serieses1, racingSim0)
	if err != nil {
		return err
	}

	racingSim0.R.SimulationSeries = append(racingSim0.R.SimulationSeries, serieses1...)

	for _, rel := range related {
		rel.R.SimulationRacingSim = racingSim0
	}

	return nil
}

func insertRacingSimSimulationSimulationCarAliases0(ctx context.Context, exec bob.Executor, simulationCarAliases1 []*SimulationCarAliasSetter, racingSim0 *RacingSim) (SimulationCarAliasSlice, error) {
	for i := range simulationCarAliases1 {
		simulationCarAliases1[i].SimulationID = omit.From(racingSim0.ID)
	}

	ret, err := SimulationCarAliases.Insert(bob.ToMods(simulationCarAliases1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertRacingSimSimulationSimulationCarAliases0: %w", err)
	}

	return ret, nil
}

func attachRacingSimSimulationSimulationCarAliases0(ctx context.Context, exec bob.Executor, count int, simulationCarAliases1 SimulationCarAliasSlice, racingSim0 *RacingSim) (SimulationCarAliasSlice, error) {
	setter := &SimulationCarAliasSetter{
		SimulationID: omit.From(racingSim0.ID),
	}

	err := simulationCarAliases1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachRacingSimSimulationSimulationCarAliases0: %w", err)
	}

	return simulationCarAliases1, nil
}

func (racingSim0 *RacingSim) InsertSimulationSimulationCarAliases(ctx context.Context, exec bob.Executor, related ...*SimulationCarAliasSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	simulationCarAliases1, err := insertRacingSimSimulationSimulationCarAliases0(ctx, exec, related, racingSim0)
	if err != nil {
		return err
	}

	racingSim0.R.SimulationSimulationCarAliases = append(racingSim0.R.SimulationSimulationCarAliases, simulationCarAliases1...)

	for _, rel := range simulationCarAliases1 {
		rel.R.SimulationRacingSim = racingSim0
	}
	return nil
}

func (racingSim0 *RacingSim) AttachSimulationSimulationCarAliases(ctx context.Context, exec bob.Executor, related ...*SimulationCarAlias) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	simulationCarAliases1 := SimulationCarAliasSlice(related)

	_, err = attachRacingSimSimulationSimulationCarAliases0(ctx, exec, len(related), simulationCarAliases1, racingSim0)
	if err != nil {
		return err
	}

	racingSim0.R.SimulationSimulationCarAliases = append(racingSim0.R.SimulationSimulationCarAliases, simulationCarAliases1...)

	for _, rel := range related {
		rel.R.SimulationRacingSim = racingSim0
	}

	return nil
}

func insertRacingSimSimulationSimulationDriverAliases0(ctx context.Context, exec bob.Executor, simulationDriverAliases1 []*SimulationDriverAliasSetter, racingSim0 *RacingSim) (SimulationDriverAliasSlice, error) {
	for i := range simulationDriverAliases1 {
		simulationDriverAliases1[i].SimulationID = omit.From(racingSim0.ID)
	}

	ret, err := SimulationDriverAliases.Insert(bob.ToMods(simulationDriverAliases1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertRacingSimSimulationSimulationDriverAliases0: %w", err)
	}

	return ret, nil
}

func attachRacingSimSimulationSimulationDriverAliases0(ctx context.Context, exec bob.Executor, count int, simulationDriverAliases1 SimulationDriverAliasSlice, racingSim0 *RacingSim) (SimulationDriverAliasSlice, error) {
	setter := &SimulationDriverAliasSetter{
		SimulationID: omit.From(racingSim0.ID),
	}

	err := simulationDriverAliases1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachRacingSimSimulationSimulationDriverAliases0: %w", err)
	}

	return simulationDriverAliases1, nil
}

func (racingSim0 *RacingSim) InsertSimulationSimulationDriverAliases(ctx context.Context, exec bob.Executor, related ...*SimulationDriverAliasSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	simulationDriverAliases1, err := insertRacingSimSimulationSimulationDriverAliases0(ctx, exec, related, racingSim0)
	if err != nil {
		return err
	}

	racingSim0.R.SimulationSimulationDriverAliases = append(racingSim0.R.SimulationSimulationDriverAliases, simulationDriverAliases1...)

	for _, rel := range simulationDriverAliases1 {
		rel.R.SimulationRacingSim = racingSim0
	}
	return nil
}

func (racingSim0 *RacingSim) AttachSimulationSimulationDriverAliases(ctx context.Context, exec bob.Executor, related ...*SimulationDriverAlias) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	simulationDriverAliases1 := SimulationDriverAliasSlice(related)

	_, err = attachRacingSimSimulationSimulationDriverAliases0(ctx, exec, len(related), simulationDriverAliases1, racingSim0)
	if err != nil {
		return err
	}

	racingSim0.R.SimulationSimulationDriverAliases = append(racingSim0.R.SimulationSimulationDriverAliases, simulationDriverAliases1...)

	for _, rel := range related {
		rel.R.SimulationRacingSim = racingSim0
	}

	return nil
}

func insertRacingSimSimulationSimulationTrackLayoutAliases0(ctx context.Context, exec bob.Executor, simulationTrackLayoutAliases1 []*SimulationTrackLayoutAliasSetter, racingSim0 *RacingSim) (SimulationTrackLayoutAliasSlice, error) {
	for i := range simulationTrackLayoutAliases1 {
		simulationTrackLayoutAliases1[i].SimulationID = omit.From(racingSim0.ID)
	}

	ret, err := SimulationTrackLayoutAliases.Insert(bob.ToMods(simulationTrackLayoutAliases1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertRacingSimSimulationSimulationTrackLayoutAliases0: %w", err)
	}

	return ret, nil
}

func attachRacingSimSimulationSimulationTrackLayoutAliases0(ctx context.Context, exec bob.Executor, count int, simulationTrackLayoutAliases1 SimulationTrackLayoutAliasSlice, racingSim0 *RacingSim) (SimulationTrackLayoutAliasSlice, error) {
	setter := &SimulationTrackLayoutAliasSetter{
		SimulationID: omit.From(racingSim0.ID),
	}

	err := simulationTrackLayoutAliases1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachRacingSimSimulationSimulationTrackLayoutAliases0: %w", err)
	}

	return simulationTrackLayoutAliases1, nil
}

func (racingSim0 *RacingSim) InsertSimulationSimulationTrackLayoutAliases(ctx context.Context, exec bob.Executor, related ...*SimulationTrackLayoutAliasSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	simulationTrackLayoutAliases1, err := insertRacingSimSimulationSimulationTrackLayoutAliases0(ctx, exec, related, racingSim0)
	if err != nil {
		return err
	}

	racingSim0.R.SimulationSimulationTrackLayoutAliases = append(racingSim0.R.SimulationSimulationTrackLayoutAliases, simulationTrackLayoutAliases1...)

	for _, rel := range simulationTrackLayoutAliases1 {
		rel.R.SimulationRacingSim = racingSim0
	}
	return nil
}

func (racingSim0 *RacingSim) AttachSimulationSimulationTrackLayoutAliases(ctx context.Context, exec bob.Executor, related ...*SimulationTrackLayoutAlias) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	simulationTrackLayoutAliases1 := SimulationTrackLayoutAliasSlice(related)

	_, err = attachRacingSimSimulationSimulationTrackLayoutAliases0(ctx, exec, len(related), simulationTrackLayoutAliases1, racingSim0)
	if err != nil {
		return err
	}

	racingSim0.R.SimulationSimulationTrackLayoutAliases = append(racingSim0.R.SimulationSimulationTrackLayoutAliases, simulationTrackLayoutAliases1...)

	for _, rel := range related {
		rel.R.SimulationRacingSim = racingSim0
	}

	return nil
}

type racingSimWhere[Q psql.Filterable] struct {
	ID                     psql.WhereMod[Q, int32]
	FrontendID             psql.WhereMod[Q, uuid.UUID]
	Name                   psql.WhereMod[Q, string]
	SupportedImportFormats psql.WhereMod[Q, pq.StringArray]
	IsActive               psql.WhereMod[Q, bool]
	CreatedAt              psql.WhereMod[Q, time.Time]
	UpdatedAt              psql.WhereMod[Q, time.Time]
	CreatedBy              psql.WhereMod[Q, string]
	UpdatedBy              psql.WhereMod[Q, string]
}

func (racingSimWhere[Q]) AliasedAs(alias string) racingSimWhere[Q] {
	return buildRacingSimWhere[Q](buildRacingSimColumns(alias))
}

func buildRacingSimWhere[Q psql.Filterable](cols racingSimColumns) racingSimWhere[Q] {
	return racingSimWhere[Q]{
		ID:                     psql.Where[Q, int32](cols.ID),
		FrontendID:             psql.Where[Q, uuid.UUID](cols.FrontendID),
		Name:                   psql.Where[Q, string](cols.Name),
		SupportedImportFormats: psql.Where[Q, pq.StringArray](cols.SupportedImportFormats),
		IsActive:               psql.Where[Q, bool](cols.IsActive),
		CreatedAt:              psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:              psql.Where[Q, time.Time](cols.UpdatedAt),
		CreatedBy:              psql.Where[Q, string](cols.CreatedBy),
		UpdatedBy:              psql.Where[Q, string](cols.UpdatedBy),
	}
}

func (o *RacingSim) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "SimulationSeries":
		rels, ok := retrieved.(SeriesSlice)
		if !ok {
			return fmt.Errorf("racingSim cannot load %T as %q", retrieved, name)
		}

		o.R.SimulationSeries = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.SimulationRacingSim = o
			}
		}
		return nil
	case "SimulationSimulationCarAliases":
		rels, ok := retrieved.(SimulationCarAliasSlice)
		if !ok {
			return fmt.Errorf("racingSim cannot load %T as %q", retrieved, name)
		}

		o.R.SimulationSimulationCarAliases = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.SimulationRacingSim = o
			}
		}
		return nil
	case "SimulationSimulationDriverAliases":
		rels, ok := retrieved.(SimulationDriverAliasSlice)
		if !ok {
			return fmt.Errorf("racingSim cannot load %T as %q", retrieved, name)
		}

		o.R.SimulationSimulationDriverAliases = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.SimulationRacingSim = o
			}
		}
		return nil
	case "SimulationSimulationTrackLayoutAliases":
		rels, ok := retrieved.(SimulationTrackLayoutAliasSlice)
		if !ok {
			return fmt.Errorf("racingSim cannot load %T as %q", retrieved, name)
		}

		o.R.SimulationSimulationTrackLayoutAliases = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.SimulationRacingSim = o
			}
		}
		return nil
	default:
		return fmt.Errorf("racingSim has no relationship %q", name)
	}
}

type racingSimPreloader struct{}

func buildRacingSimPreloader() racingSimPreloader {
	return racingSimPreloader{}
}

type racingSimThenLoader[Q orm.Loadable] struct {
	SimulationSeries                       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	SimulationSimulationCarAliases         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	SimulationSimulationDriverAliases      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	SimulationSimulationTrackLayoutAliases func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildRacingSimThenLoader[Q orm.Loadable]() racingSimThenLoader[Q] {
	type SimulationSeriesLoadInterface interface {
		LoadSimulationSeries(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type SimulationSimulationCarAliasesLoadInterface interface {
		LoadSimulationSimulationCarAliases(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type SimulationSimulationDriverAliasesLoadInterface interface {
		LoadSimulationSimulationDriverAliases(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type SimulationSimulationTrackLayoutAliasesLoadInterface interface {
		LoadSimulationSimulationTrackLayoutAliases(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return racingSimThenLoader[Q]{
		SimulationSeries: thenLoadBuilder[Q](
			"SimulationSeries",
			func(ctx context.Context, exec bob.Executor, retrieved SimulationSeriesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSimulationSeries(ctx, exec, mods...)
			},
		),
		SimulationSimulationCarAliases: thenLoadBuilder[Q](
			"SimulationSimulationCarAliases",
			func(ctx context.Context, exec bob.Executor, retrieved SimulationSimulationCarAliasesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSimulationSimulationCarAliases(ctx, exec, mods...)
			},
		),
		SimulationSimulationDriverAliases: thenLoadBuilder[Q](
			"SimulationSimulationDriverAliases",
			func(ctx context.Context, exec bob.Executor, retrieved SimulationSimulationDriverAliasesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSimulationSimulationDriverAliases(ctx, exec, mods...)
			},
		),
		SimulationSimulationTrackLayoutAliases: thenLoadBuilder[Q](
			"SimulationSimulationTrackLayoutAliases",
			func(ctx context.Context, exec bob.Executor, retrieved SimulationSimulationTrackLayoutAliasesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSimulationSimulationTrackLayoutAliases(ctx, exec, mods...)
			},
		),
	}
}

// LoadSimulationSeries loads the racingSim's SimulationSeries into the .R struct
func (o *RacingSim) LoadSimulationSeries(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.SimulationSeries = nil

	related, err := o.SimulationSeries(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.SimulationRacingSim = o
	}

	o.R.SimulationSeries = related
	return nil
}

// LoadSimulationSeries loads the racingSim's SimulationSeries into the .R struct
func (os RacingSimSlice) LoadSimulationSeries(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	serieses, err := os.SimulationSeries(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.SimulationSeries = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range serieses {

			if !(o.ID == rel.SimulationID) {
				continue
			}

			rel.R.SimulationRacingSim = o

			o.R.SimulationSeries = append(o.R.SimulationSeries, rel)
		}
	}

	return nil
}

// LoadSimulationSimulationCarAliases loads the racingSim's SimulationSimulationCarAliases into the .R struct
func (o *RacingSim) LoadSimulationSimulationCarAliases(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.SimulationSimulationCarAliases = nil

	related, err := o.SimulationSimulationCarAliases(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.SimulationRacingSim = o
	}

	o.R.SimulationSimulationCarAliases = related
	return nil
}

// LoadSimulationSimulationCarAliases loads the racingSim's SimulationSimulationCarAliases into the .R struct
func (os RacingSimSlice) LoadSimulationSimulationCarAliases(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	simulationCarAliases, err := os.SimulationSimulationCarAliases(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.SimulationSimulationCarAliases = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range simulationCarAliases {

			if !(o.ID == rel.SimulationID) {
				continue
			}

			rel.R.SimulationRacingSim = o

			o.R.SimulationSimulationCarAliases = append(o.R.SimulationSimulationCarAliases, rel)
		}
	}

	return nil
}

// LoadSimulationSimulationDriverAliases loads the racingSim's SimulationSimulationDriverAliases into the .R struct
func (o *RacingSim) LoadSimulationSimulationDriverAliases(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.SimulationSimulationDriverAliases = nil

	related, err := o.SimulationSimulationDriverAliases(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.SimulationRacingSim = o
	}

	o.R.SimulationSimulationDriverAliases = related
	return nil
}

// LoadSimulationSimulationDriverAliases loads the racingSim's SimulationSimulationDriverAliases into the .R struct
func (os RacingSimSlice) LoadSimulationSimulationDriverAliases(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	simulationDriverAliases, err := os.SimulationSimulationDriverAliases(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.SimulationSimulationDriverAliases = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range simulationDriverAliases {

			if !(o.ID == rel.SimulationID) {
				continue
			}

			rel.R.SimulationRacingSim = o

			o.R.SimulationSimulationDriverAliases = append(o.R.SimulationSimulationDriverAliases, rel)
		}
	}

	return nil
}

// LoadSimulationSimulationTrackLayoutAliases loads the racingSim's SimulationSimulationTrackLayoutAliases into the .R struct
func (o *RacingSim) LoadSimulationSimulationTrackLayoutAliases(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.SimulationSimulationTrackLayoutAliases = nil

	related, err := o.SimulationSimulationTrackLayoutAliases(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.SimulationRacingSim = o
	}

	o.R.SimulationSimulationTrackLayoutAliases = related
	return nil
}

// LoadSimulationSimulationTrackLayoutAliases loads the racingSim's SimulationSimulationTrackLayoutAliases into the .R struct
func (os RacingSimSlice) LoadSimulationSimulationTrackLayoutAliases(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	simulationTrackLayoutAliases, err := os.SimulationSimulationTrackLayoutAliases(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.SimulationSimulationTrackLayoutAliases = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range simulationTrackLayoutAliases {

			if !(o.ID == rel.SimulationID) {
				continue
			}

			rel.R.SimulationRacingSim = o

			o.R.SimulationSimulationTrackLayoutAliases = append(o.R.SimulationSimulationTrackLayoutAliases, rel)
		}
	}

	return nil
}

type racingSimJoins[Q dialect.Joinable] struct {
	typ                                    string
	SimulationSeries                       modAs[Q, seriesColumns]
	SimulationSimulationCarAliases         modAs[Q, simulationCarAliasColumns]
	SimulationSimulationDriverAliases      modAs[Q, simulationDriverAliasColumns]
	SimulationSimulationTrackLayoutAliases modAs[Q, simulationTrackLayoutAliasColumns]
}

func (j racingSimJoins[Q]) aliasedAs(alias string) racingSimJoins[Q] {
	return buildRacingSimJoins[Q](buildRacingSimColumns(alias), j.typ)
}

func buildRacingSimJoins[Q dialect.Joinable](cols racingSimColumns, typ string) racingSimJoins[Q] {
	return racingSimJoins[Q]{
		typ: typ,
		SimulationSeries: modAs[Q, seriesColumns]{
			c: Serieses.Columns,
			f: func(to seriesColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Serieses.Name().As(to.Alias())).On(
						to.SimulationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		SimulationSimulationCarAliases: modAs[Q, simulationCarAliasColumns]{
			c: SimulationCarAliases.Columns,
			f: func(to simulationCarAliasColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, SimulationCarAliases.Name().As(to.Alias())).On(
						to.SimulationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		SimulationSimulationDriverAliases: modAs[Q, simulationDriverAliasColumns]{
			c: SimulationDriverAliases.Columns,
			f: func(to simulationDriverAliasColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, SimulationDriverAliases.Name().As(to.Alias())).On(
						to.SimulationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		SimulationSimulationTrackLayoutAliases: modAs[Q, simulationTrackLayoutAliasColumns]{
			c: SimulationTrackLayoutAliases.Columns,
			f: func(to simulationTrackLayoutAliasColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, SimulationTrackLayoutAliases.Name().As(to.Alias())).On(
						to.SimulationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
