// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// SimulationTrackLayoutAlias is an object representing the database table.
type SimulationTrackLayoutAlias struct {
	ID            int32     `db:"id,pk" `
	TrackLayoutID int32     `db:"track_layout_id" `
	SimulationID  int32     `db:"simulation_id" `
	ExternalName  string    `db:"external_name" `
	CreatedAt     time.Time `db:"created_at" `
	UpdatedAt     time.Time `db:"updated_at" `
	CreatedBy     string    `db:"created_by" `
	UpdatedBy     string    `db:"updated_by" `

	R simulationTrackLayoutAliasR `db:"-" `
}

// SimulationTrackLayoutAliasSlice is an alias for a slice of pointers to SimulationTrackLayoutAlias.
// This should almost always be used instead of []*SimulationTrackLayoutAlias.
type SimulationTrackLayoutAliasSlice []*SimulationTrackLayoutAlias

// SimulationTrackLayoutAliases contains methods to work with the simulation_track_layout_aliases table
var SimulationTrackLayoutAliases = psql.NewTablex[*SimulationTrackLayoutAlias, SimulationTrackLayoutAliasSlice, *SimulationTrackLayoutAliasSetter]("", "simulation_track_layout_aliases", buildSimulationTrackLayoutAliasColumns("simulation_track_layout_aliases"))

// SimulationTrackLayoutAliasesQuery is a query on the simulation_track_layout_aliases table
type SimulationTrackLayoutAliasesQuery = *psql.ViewQuery[*SimulationTrackLayoutAlias, SimulationTrackLayoutAliasSlice]

// simulationTrackLayoutAliasR is where relationships are stored.
type simulationTrackLayoutAliasR struct {
	SimulationRacingSim *RacingSim   // simulation_track_layout_aliases.simulation_track_layout_aliases_simulation_id_fk
	TrackLayout         *TrackLayout // simulation_track_layout_aliases.simulation_track_layout_aliases_track_layout_id_fk
}

func buildSimulationTrackLayoutAliasColumns(tableName string) simulationTrackLayoutAliasColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "track_layout_id", "simulation_id", "external_name", "created_at", "updated_at", "created_by", "updated_by",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return simulationTrackLayoutAliasColumns{
		ColumnsExpr:   columnsExpr,
		tableAlias:    tableName,
		ID:            psql.Quote(tableName, "id"),
		TrackLayoutID: psql.Quote(tableName, "track_layout_id"),
		SimulationID:  psql.Quote(tableName, "simulation_id"),
		ExternalName:  psql.Quote(tableName, "external_name"),
		CreatedAt:     psql.Quote(tableName, "created_at"),
		UpdatedAt:     psql.Quote(tableName, "updated_at"),
		CreatedBy:     psql.Quote(tableName, "created_by"),
		UpdatedBy:     psql.Quote(tableName, "updated_by"),
	}
}

type simulationTrackLayoutAliasColumns struct {
	expr.ColumnsExpr
	tableAlias    string
	ID            psql.Expression
	TrackLayoutID psql.Expression
	SimulationID  psql.Expression
	ExternalName  psql.Expression
	CreatedAt     psql.Expression
	UpdatedAt     psql.Expression
	CreatedBy     psql.Expression
	UpdatedBy     psql.Expression
}

func (c simulationTrackLayoutAliasColumns) Alias() string {
	return c.tableAlias
}

func (simulationTrackLayoutAliasColumns) AliasedAs(tableName string) simulationTrackLayoutAliasColumns {
	return buildSimulationTrackLayoutAliasColumns(tableName)
}

func (c simulationTrackLayoutAliasColumns) Unqualified() simulationTrackLayoutAliasColumns {
	return buildSimulationTrackLayoutAliasColumns("")
}

// SimulationTrackLayoutAliasSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SimulationTrackLayoutAliasSetter struct {
	ID            omit.Val[int32]     `db:"id,pk" `
	TrackLayoutID omit.Val[int32]     `db:"track_layout_id" `
	SimulationID  omit.Val[int32]     `db:"simulation_id" `
	ExternalName  omit.Val[string]    `db:"external_name" `
	CreatedAt     omit.Val[time.Time] `db:"created_at" `
	UpdatedAt     omit.Val[time.Time] `db:"updated_at" `
	CreatedBy     omit.Val[string]    `db:"created_by" `
	UpdatedBy     omit.Val[string]    `db:"updated_by" `
}

func (s SimulationTrackLayoutAliasSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.TrackLayoutID.IsValue() {
		vals = append(vals, "track_layout_id")
	}
	if s.SimulationID.IsValue() {
		vals = append(vals, "simulation_id")
	}
	if s.ExternalName.IsValue() {
		vals = append(vals, "external_name")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if s.CreatedBy.IsValue() {
		vals = append(vals, "created_by")
	}
	if s.UpdatedBy.IsValue() {
		vals = append(vals, "updated_by")
	}
	return vals
}

func (s SimulationTrackLayoutAliasSetter) Overwrite(t *SimulationTrackLayoutAlias) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.TrackLayoutID.IsValue() {
		t.TrackLayoutID = s.TrackLayoutID.MustGet()
	}
	if s.SimulationID.IsValue() {
		t.SimulationID = s.SimulationID.MustGet()
	}
	if s.ExternalName.IsValue() {
		t.ExternalName = s.ExternalName.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if s.CreatedBy.IsValue() {
		t.CreatedBy = s.CreatedBy.MustGet()
	}
	if s.UpdatedBy.IsValue() {
		t.UpdatedBy = s.UpdatedBy.MustGet()
	}
}

func (s *SimulationTrackLayoutAliasSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return SimulationTrackLayoutAliases.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.TrackLayoutID.IsValue() {
			vals[1] = psql.Arg(s.TrackLayoutID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.SimulationID.IsValue() {
			vals[2] = psql.Arg(s.SimulationID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.ExternalName.IsValue() {
			vals[3] = psql.Arg(s.ExternalName.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[4] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[5] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedBy.IsValue() {
			vals[6] = psql.Arg(s.CreatedBy.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.UpdatedBy.IsValue() {
			vals[7] = psql.Arg(s.UpdatedBy.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s SimulationTrackLayoutAliasSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SimulationTrackLayoutAliasSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.TrackLayoutID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "track_layout_id")...),
			psql.Arg(s.TrackLayoutID),
		}})
	}

	if s.SimulationID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "simulation_id")...),
			psql.Arg(s.SimulationID),
		}})
	}

	if s.ExternalName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "external_name")...),
			psql.Arg(s.ExternalName),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.CreatedBy.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_by")...),
			psql.Arg(s.CreatedBy),
		}})
	}

	if s.UpdatedBy.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_by")...),
			psql.Arg(s.UpdatedBy),
		}})
	}

	return exprs
}

// FindSimulationTrackLayoutAlias retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSimulationTrackLayoutAlias(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*SimulationTrackLayoutAlias, error) {
	if len(cols) == 0 {
		return SimulationTrackLayoutAliases.Query(
			sm.Where(SimulationTrackLayoutAliases.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return SimulationTrackLayoutAliases.Query(
		sm.Where(SimulationTrackLayoutAliases.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(SimulationTrackLayoutAliases.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SimulationTrackLayoutAliasExists checks the presence of a single record by primary key
func SimulationTrackLayoutAliasExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return SimulationTrackLayoutAliases.Query(
		sm.Where(SimulationTrackLayoutAliases.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after SimulationTrackLayoutAlias is retrieved from the database
func (o *SimulationTrackLayoutAlias) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SimulationTrackLayoutAliases.AfterSelectHooks.RunHooks(ctx, exec, SimulationTrackLayoutAliasSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = SimulationTrackLayoutAliases.AfterInsertHooks.RunHooks(ctx, exec, SimulationTrackLayoutAliasSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = SimulationTrackLayoutAliases.AfterUpdateHooks.RunHooks(ctx, exec, SimulationTrackLayoutAliasSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = SimulationTrackLayoutAliases.AfterDeleteHooks.RunHooks(ctx, exec, SimulationTrackLayoutAliasSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = SimulationTrackLayoutAliases.AfterMergeHooks.RunHooks(ctx, exec, SimulationTrackLayoutAliasSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the SimulationTrackLayoutAlias
func (o *SimulationTrackLayoutAlias) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *SimulationTrackLayoutAlias) pkEQ() dialect.Expression {
	return psql.Quote("simulation_track_layout_aliases", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the SimulationTrackLayoutAlias
func (o *SimulationTrackLayoutAlias) Update(ctx context.Context, exec bob.Executor, s *SimulationTrackLayoutAliasSetter) error {
	v, err := SimulationTrackLayoutAliases.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single SimulationTrackLayoutAlias record with an executor
func (o *SimulationTrackLayoutAlias) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := SimulationTrackLayoutAliases.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the SimulationTrackLayoutAlias using the executor
func (o *SimulationTrackLayoutAlias) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := SimulationTrackLayoutAliases.Query(
		sm.Where(SimulationTrackLayoutAliases.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after SimulationTrackLayoutAliasSlice is retrieved from the database
func (o SimulationTrackLayoutAliasSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SimulationTrackLayoutAliases.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = SimulationTrackLayoutAliases.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = SimulationTrackLayoutAliases.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = SimulationTrackLayoutAliases.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = SimulationTrackLayoutAliases.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o SimulationTrackLayoutAliasSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("simulation_track_layout_aliases", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SimulationTrackLayoutAliasSlice) copyMatchingRows(from ...*SimulationTrackLayoutAlias) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SimulationTrackLayoutAliasSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SimulationTrackLayoutAliases.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SimulationTrackLayoutAlias:
				o.copyMatchingRows(retrieved)
			case []*SimulationTrackLayoutAlias:
				o.copyMatchingRows(retrieved...)
			case SimulationTrackLayoutAliasSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SimulationTrackLayoutAlias or a slice of SimulationTrackLayoutAlias
				// then run the AfterUpdateHooks on the slice
				_, err = SimulationTrackLayoutAliases.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SimulationTrackLayoutAliasSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SimulationTrackLayoutAliases.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SimulationTrackLayoutAlias:
				o.copyMatchingRows(retrieved)
			case []*SimulationTrackLayoutAlias:
				o.copyMatchingRows(retrieved...)
			case SimulationTrackLayoutAliasSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SimulationTrackLayoutAlias or a slice of SimulationTrackLayoutAlias
				// then run the AfterDeleteHooks on the slice
				_, err = SimulationTrackLayoutAliases.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o SimulationTrackLayoutAliasSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SimulationTrackLayoutAliases.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SimulationTrackLayoutAlias:
				o.copyMatchingRows(retrieved)
			case []*SimulationTrackLayoutAlias:
				o.copyMatchingRows(retrieved...)
			case SimulationTrackLayoutAliasSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SimulationTrackLayoutAlias or a slice of SimulationTrackLayoutAlias
				// then run the AfterMergeHooks on the slice
				_, err = SimulationTrackLayoutAliases.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o SimulationTrackLayoutAliasSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SimulationTrackLayoutAliasSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SimulationTrackLayoutAliases.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SimulationTrackLayoutAliasSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SimulationTrackLayoutAliases.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SimulationTrackLayoutAliasSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := SimulationTrackLayoutAliases.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// SimulationRacingSim starts a query for related objects on racing_sims
func (o *SimulationTrackLayoutAlias) SimulationRacingSim(mods ...bob.Mod[*dialect.SelectQuery]) RacingSimsQuery {
	return RacingSims.Query(append(mods,
		sm.Where(RacingSims.Columns.ID.EQ(psql.Arg(o.SimulationID))),
	)...)
}

func (os SimulationTrackLayoutAliasSlice) SimulationRacingSim(mods ...bob.Mod[*dialect.SelectQuery]) RacingSimsQuery {
	pkSimulationID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkSimulationID = append(pkSimulationID, o.SimulationID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkSimulationID), "integer[]")),
	))

	return RacingSims.Query(append(mods,
		sm.Where(psql.Group(RacingSims.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// TrackLayout starts a query for related objects on track_layouts
func (o *SimulationTrackLayoutAlias) TrackLayout(mods ...bob.Mod[*dialect.SelectQuery]) TrackLayoutsQuery {
	return TrackLayouts.Query(append(mods,
		sm.Where(TrackLayouts.Columns.ID.EQ(psql.Arg(o.TrackLayoutID))),
	)...)
}

func (os SimulationTrackLayoutAliasSlice) TrackLayout(mods ...bob.Mod[*dialect.SelectQuery]) TrackLayoutsQuery {
	pkTrackLayoutID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkTrackLayoutID = append(pkTrackLayoutID, o.TrackLayoutID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkTrackLayoutID), "integer[]")),
	))

	return TrackLayouts.Query(append(mods,
		sm.Where(psql.Group(TrackLayouts.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachSimulationTrackLayoutAliasSimulationRacingSim0(ctx context.Context, exec bob.Executor, count int, simulationTrackLayoutAlias0 *SimulationTrackLayoutAlias, racingSim1 *RacingSim) (*SimulationTrackLayoutAlias, error) {
	setter := &SimulationTrackLayoutAliasSetter{
		SimulationID: omit.From(racingSim1.ID),
	}

	err := simulationTrackLayoutAlias0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachSimulationTrackLayoutAliasSimulationRacingSim0: %w", err)
	}

	return simulationTrackLayoutAlias0, nil
}

func (simulationTrackLayoutAlias0 *SimulationTrackLayoutAlias) InsertSimulationRacingSim(ctx context.Context, exec bob.Executor, related *RacingSimSetter) error {
	var err error

	racingSim1, err := RacingSims.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachSimulationTrackLayoutAliasSimulationRacingSim0(ctx, exec, 1, simulationTrackLayoutAlias0, racingSim1)
	if err != nil {
		return err
	}

	simulationTrackLayoutAlias0.R.SimulationRacingSim = racingSim1

	racingSim1.R.SimulationSimulationTrackLayoutAliases = append(racingSim1.R.SimulationSimulationTrackLayoutAliases, simulationTrackLayoutAlias0)

	return nil
}

func (simulationTrackLayoutAlias0 *SimulationTrackLayoutAlias) AttachSimulationRacingSim(ctx context.Context, exec bob.Executor, racingSim1 *RacingSim) error {
	var err error

	_, err = attachSimulationTrackLayoutAliasSimulationRacingSim0(ctx, exec, 1, simulationTrackLayoutAlias0, racingSim1)
	if err != nil {
		return err
	}

	simulationTrackLayoutAlias0.R.SimulationRacingSim = racingSim1

	racingSim1.R.SimulationSimulationTrackLayoutAliases = append(racingSim1.R.SimulationSimulationTrackLayoutAliases, simulationTrackLayoutAlias0)

	return nil
}

func attachSimulationTrackLayoutAliasTrackLayout0(ctx context.Context, exec bob.Executor, count int, simulationTrackLayoutAlias0 *SimulationTrackLayoutAlias, trackLayout1 *TrackLayout) (*SimulationTrackLayoutAlias, error) {
	setter := &SimulationTrackLayoutAliasSetter{
		TrackLayoutID: omit.From(trackLayout1.ID),
	}

	err := simulationTrackLayoutAlias0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachSimulationTrackLayoutAliasTrackLayout0: %w", err)
	}

	return simulationTrackLayoutAlias0, nil
}

func (simulationTrackLayoutAlias0 *SimulationTrackLayoutAlias) InsertTrackLayout(ctx context.Context, exec bob.Executor, related *TrackLayoutSetter) error {
	var err error

	trackLayout1, err := TrackLayouts.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachSimulationTrackLayoutAliasTrackLayout0(ctx, exec, 1, simulationTrackLayoutAlias0, trackLayout1)
	if err != nil {
		return err
	}

	simulationTrackLayoutAlias0.R.TrackLayout = trackLayout1

	trackLayout1.R.SimulationTrackLayoutAliases = append(trackLayout1.R.SimulationTrackLayoutAliases, simulationTrackLayoutAlias0)

	return nil
}

func (simulationTrackLayoutAlias0 *SimulationTrackLayoutAlias) AttachTrackLayout(ctx context.Context, exec bob.Executor, trackLayout1 *TrackLayout) error {
	var err error

	_, err = attachSimulationTrackLayoutAliasTrackLayout0(ctx, exec, 1, simulationTrackLayoutAlias0, trackLayout1)
	if err != nil {
		return err
	}

	simulationTrackLayoutAlias0.R.TrackLayout = trackLayout1

	trackLayout1.R.SimulationTrackLayoutAliases = append(trackLayout1.R.SimulationTrackLayoutAliases, simulationTrackLayoutAlias0)

	return nil
}

type simulationTrackLayoutAliasWhere[Q psql.Filterable] struct {
	ID            psql.WhereMod[Q, int32]
	TrackLayoutID psql.WhereMod[Q, int32]
	SimulationID  psql.WhereMod[Q, int32]
	ExternalName  psql.WhereMod[Q, string]
	CreatedAt     psql.WhereMod[Q, time.Time]
	UpdatedAt     psql.WhereMod[Q, time.Time]
	CreatedBy     psql.WhereMod[Q, string]
	UpdatedBy     psql.WhereMod[Q, string]
}

func (simulationTrackLayoutAliasWhere[Q]) AliasedAs(alias string) simulationTrackLayoutAliasWhere[Q] {
	return buildSimulationTrackLayoutAliasWhere[Q](buildSimulationTrackLayoutAliasColumns(alias))
}

func buildSimulationTrackLayoutAliasWhere[Q psql.Filterable](cols simulationTrackLayoutAliasColumns) simulationTrackLayoutAliasWhere[Q] {
	return simulationTrackLayoutAliasWhere[Q]{
		ID:            psql.Where[Q, int32](cols.ID),
		TrackLayoutID: psql.Where[Q, int32](cols.TrackLayoutID),
		SimulationID:  psql.Where[Q, int32](cols.SimulationID),
		ExternalName:  psql.Where[Q, string](cols.ExternalName),
		CreatedAt:     psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:     psql.Where[Q, time.Time](cols.UpdatedAt),
		CreatedBy:     psql.Where[Q, string](cols.CreatedBy),
		UpdatedBy:     psql.Where[Q, string](cols.UpdatedBy),
	}
}

func (o *SimulationTrackLayoutAlias) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "SimulationRacingSim":
		rel, ok := retrieved.(*RacingSim)
		if !ok {
			return fmt.Errorf("simulationTrackLayoutAlias cannot load %T as %q", retrieved, name)
		}

		o.R.SimulationRacingSim = rel

		if rel != nil {
			rel.R.SimulationSimulationTrackLayoutAliases = SimulationTrackLayoutAliasSlice{o}
		}
		return nil
	case "TrackLayout":
		rel, ok := retrieved.(*TrackLayout)
		if !ok {
			return fmt.Errorf("simulationTrackLayoutAlias cannot load %T as %q", retrieved, name)
		}

		o.R.TrackLayout = rel

		if rel != nil {
			rel.R.SimulationTrackLayoutAliases = SimulationTrackLayoutAliasSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("simulationTrackLayoutAlias has no relationship %q", name)
	}
}

type simulationTrackLayoutAliasPreloader struct {
	SimulationRacingSim func(...psql.PreloadOption) psql.Preloader
	TrackLayout         func(...psql.PreloadOption) psql.Preloader
}

func buildSimulationTrackLayoutAliasPreloader() simulationTrackLayoutAliasPreloader {
	return simulationTrackLayoutAliasPreloader{
		SimulationRacingSim: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*RacingSim, RacingSimSlice](psql.PreloadRel{
				Name: "SimulationRacingSim",
				Sides: []psql.PreloadSide{
					{
						From:        SimulationTrackLayoutAliases,
						To:          RacingSims,
						FromColumns: []string{"simulation_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, RacingSims.Columns.Names(), opts...)
		},
		TrackLayout: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*TrackLayout, TrackLayoutSlice](psql.PreloadRel{
				Name: "TrackLayout",
				Sides: []psql.PreloadSide{
					{
						From:        SimulationTrackLayoutAliases,
						To:          TrackLayouts,
						FromColumns: []string{"track_layout_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, TrackLayouts.Columns.Names(), opts...)
		},
	}
}

type simulationTrackLayoutAliasThenLoader[Q orm.Loadable] struct {
	SimulationRacingSim func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	TrackLayout         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildSimulationTrackLayoutAliasThenLoader[Q orm.Loadable]() simulationTrackLayoutAliasThenLoader[Q] {
	type SimulationRacingSimLoadInterface interface {
		LoadSimulationRacingSim(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TrackLayoutLoadInterface interface {
		LoadTrackLayout(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return simulationTrackLayoutAliasThenLoader[Q]{
		SimulationRacingSim: thenLoadBuilder[Q](
			"SimulationRacingSim",
			func(ctx context.Context, exec bob.Executor, retrieved SimulationRacingSimLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSimulationRacingSim(ctx, exec, mods...)
			},
		),
		TrackLayout: thenLoadBuilder[Q](
			"TrackLayout",
			func(ctx context.Context, exec bob.Executor, retrieved TrackLayoutLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTrackLayout(ctx, exec, mods...)
			},
		),
	}
}

// LoadSimulationRacingSim loads the simulationTrackLayoutAlias's SimulationRacingSim into the .R struct
func (o *SimulationTrackLayoutAlias) LoadSimulationRacingSim(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.SimulationRacingSim = nil

	related, err := o.SimulationRacingSim(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.SimulationSimulationTrackLayoutAliases = SimulationTrackLayoutAliasSlice{o}

	o.R.SimulationRacingSim = related
	return nil
}

// LoadSimulationRacingSim loads the simulationTrackLayoutAlias's SimulationRacingSim into the .R struct
func (os SimulationTrackLayoutAliasSlice) LoadSimulationRacingSim(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	racingSims, err := os.SimulationRacingSim(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range racingSims {

			if !(o.SimulationID == rel.ID) {
				continue
			}

			rel.R.SimulationSimulationTrackLayoutAliases = append(rel.R.SimulationSimulationTrackLayoutAliases, o)

			o.R.SimulationRacingSim = rel
			break
		}
	}

	return nil
}

// LoadTrackLayout loads the simulationTrackLayoutAlias's TrackLayout into the .R struct
func (o *SimulationTrackLayoutAlias) LoadTrackLayout(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.TrackLayout = nil

	related, err := o.TrackLayout(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.SimulationTrackLayoutAliases = SimulationTrackLayoutAliasSlice{o}

	o.R.TrackLayout = related
	return nil
}

// LoadTrackLayout loads the simulationTrackLayoutAlias's TrackLayout into the .R struct
func (os SimulationTrackLayoutAliasSlice) LoadTrackLayout(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	trackLayouts, err := os.TrackLayout(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range trackLayouts {

			if !(o.TrackLayoutID == rel.ID) {
				continue
			}

			rel.R.SimulationTrackLayoutAliases = append(rel.R.SimulationTrackLayoutAliases, o)

			o.R.TrackLayout = rel
			break
		}
	}

	return nil
}

type simulationTrackLayoutAliasJoins[Q dialect.Joinable] struct {
	typ                 string
	SimulationRacingSim modAs[Q, racingSimColumns]
	TrackLayout         modAs[Q, trackLayoutColumns]
}

func (j simulationTrackLayoutAliasJoins[Q]) aliasedAs(alias string) simulationTrackLayoutAliasJoins[Q] {
	return buildSimulationTrackLayoutAliasJoins[Q](buildSimulationTrackLayoutAliasColumns(alias), j.typ)
}

func buildSimulationTrackLayoutAliasJoins[Q dialect.Joinable](cols simulationTrackLayoutAliasColumns, typ string) simulationTrackLayoutAliasJoins[Q] {
	return simulationTrackLayoutAliasJoins[Q]{
		typ: typ,
		SimulationRacingSim: modAs[Q, racingSimColumns]{
			c: RacingSims.Columns,
			f: func(to racingSimColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, RacingSims.Name().As(to.Alias())).On(
						to.ID.EQ(cols.SimulationID),
					))
				}

				return mods
			},
		},
		TrackLayout: modAs[Q, trackLayoutColumns]{
			c: TrackLayouts.Columns,
			f: func(to trackLayoutColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, TrackLayouts.Name().As(to.Alias())).On(
						to.ID.EQ(cols.TrackLayoutID),
					))
				}

				return mods
			},
		},
	}
}
