// Code generated by BobGen psql v0.46.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	models "github.com/srlmgr/backend/db/models"
)

func TestCreateBookingEntry(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewBookingEntryWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating BookingEntry: %v", err)
	}
}

func TestCreateCarBrand(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewCarBrandWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarBrand: %v", err)
	}
}

func TestCreateCarBrandWithBrandCarModelsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarBrands.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarBrands: %v", err)
	}

	if _, err := New().NewCarBrandWithContext(ctx, CarBrandMods.WithNewBrandCarModels(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarBrand with BrandCarModels: %v", err)
	}

	after, err := models.CarBrands.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarBrands: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarBrands to increase by 1, got %d", got)
	}
}

func TestCreateCarClass(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewCarClassWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarClass: %v", err)
	}
}

func TestCreateCarClassWithBookingEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarClasses.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarClasses: %v", err)
	}

	if _, err := New().NewCarClassWithContext(ctx, CarClassMods.WithNewBookingEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarClass with BookingEntries: %v", err)
	}

	after, err := models.CarClasses.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarClasses: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarClasses to increase by 1, got %d", got)
	}
}

func TestCreateCarClassWithCarClassesToCarModelsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarClasses.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarClasses: %v", err)
	}

	if _, err := New().NewCarClassWithContext(ctx, CarClassMods.WithNewCarClassesToCarModels(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarClass with CarClassesToCarModels: %v", err)
	}

	after, err := models.CarClasses.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarClasses: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarClasses to increase by 1, got %d", got)
	}
}

func TestCreateCarClassWithResultEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarClasses.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarClasses: %v", err)
	}

	if _, err := New().NewCarClassWithContext(ctx, CarClassMods.WithNewResultEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarClass with ResultEntries: %v", err)
	}

	after, err := models.CarClasses.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarClasses: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarClasses to increase by 1, got %d", got)
	}
}

func TestCreateCarClassWithSeasonCarClassesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarClasses.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarClasses: %v", err)
	}

	if _, err := New().NewCarClassWithContext(ctx, CarClassMods.WithNewSeasonCarClasses(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarClass with SeasonCarClasses: %v", err)
	}

	after, err := models.CarClasses.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarClasses: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarClasses to increase by 1, got %d", got)
	}
}

func TestCreateCarClassesToCarModel(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewCarClassesToCarModelWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarClassesToCarModel: %v", err)
	}
}

func TestCreateCarManufacturer(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewCarManufacturerWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarManufacturer: %v", err)
	}
}

func TestCreateCarManufacturerWithManufacturerCarBrandsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarManufacturers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarManufacturers: %v", err)
	}

	if _, err := New().NewCarManufacturerWithContext(ctx, CarManufacturerMods.WithNewManufacturerCarBrands(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarManufacturer with ManufacturerCarBrands: %v", err)
	}

	after, err := models.CarManufacturers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarManufacturers: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarManufacturers to increase by 1, got %d", got)
	}
}

func TestCreateCarModel(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewCarModelWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarModel: %v", err)
	}
}

func TestCreateCarModelWithCarClassesToCarModelsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if _, err := New().NewCarModelWithContext(ctx, CarModelMods.WithNewCarClassesToCarModels(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarModel with CarClassesToCarModels: %v", err)
	}

	after, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarModels to increase by 1, got %d", got)
	}
}

func TestCreateCarModelWithResultEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if _, err := New().NewCarModelWithContext(ctx, CarModelMods.WithNewResultEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarModel with ResultEntries: %v", err)
	}

	after, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarModels to increase by 1, got %d", got)
	}
}

func TestCreateCarModelWithSeasonCarModelsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if _, err := New().NewCarModelWithContext(ctx, CarModelMods.WithNewSeasonCarModels(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarModel with SeasonCarModels: %v", err)
	}

	after, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarModels to increase by 1, got %d", got)
	}
}

func TestCreateCarModelWithSeasonDriversDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if _, err := New().NewCarModelWithContext(ctx, CarModelMods.WithNewSeasonDrivers(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarModel with SeasonDrivers: %v", err)
	}

	after, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarModels to increase by 1, got %d", got)
	}
}

func TestCreateCarModelWithSimulationCarAliasesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if _, err := New().NewCarModelWithContext(ctx, CarModelMods.WithNewSimulationCarAliases(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarModel with SimulationCarAliases: %v", err)
	}

	after, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarModels to increase by 1, got %d", got)
	}
}

func TestCreateCarModelWithTeamsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if _, err := New().NewCarModelWithContext(ctx, CarModelMods.WithNewTeams(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating CarModel with Teams: %v", err)
	}

	after, err := models.CarModels.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting CarModels: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected CarModels to increase by 1, got %d", got)
	}
}

func TestCreateDriver(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewDriverWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Driver: %v", err)
	}
}

func TestCreateDriverWithBookingEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if _, err := New().NewDriverWithContext(ctx, DriverMods.WithNewBookingEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Driver with BookingEntries: %v", err)
	}

	after, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Drivers to increase by 1, got %d", got)
	}
}

func TestCreateDriverWithEventDriverStandingsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if _, err := New().NewDriverWithContext(ctx, DriverMods.WithNewEventDriverStandings(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Driver with EventDriverStandings: %v", err)
	}

	after, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Drivers to increase by 1, got %d", got)
	}
}

func TestCreateDriverWithResultEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if _, err := New().NewDriverWithContext(ctx, DriverMods.WithNewResultEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Driver with ResultEntries: %v", err)
	}

	after, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Drivers to increase by 1, got %d", got)
	}
}

func TestCreateDriverWithSeasonDriverStandingsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if _, err := New().NewDriverWithContext(ctx, DriverMods.WithNewSeasonDriverStandings(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Driver with SeasonDriverStandings: %v", err)
	}

	after, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Drivers to increase by 1, got %d", got)
	}
}

func TestCreateDriverWithSeasonDriversDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if _, err := New().NewDriverWithContext(ctx, DriverMods.WithNewSeasonDrivers(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Driver with SeasonDrivers: %v", err)
	}

	after, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Drivers to increase by 1, got %d", got)
	}
}

func TestCreateDriverWithSimulationDriverAliasesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if _, err := New().NewDriverWithContext(ctx, DriverMods.WithNewSimulationDriverAliases(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Driver with SimulationDriverAliases: %v", err)
	}

	after, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Drivers to increase by 1, got %d", got)
	}
}

func TestCreateDriverWithTeamDriversDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if _, err := New().NewDriverWithContext(ctx, DriverMods.WithNewTeamDrivers(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Driver with TeamDrivers: %v", err)
	}

	after, err := models.Drivers.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Drivers: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Drivers to increase by 1, got %d", got)
	}
}

func TestCreateEventDriverStanding(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewEventDriverStandingWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating EventDriverStanding: %v", err)
	}
}

func TestCreateEventProcessingAudit(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewEventProcessingAuditWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating EventProcessingAudit: %v", err)
	}
}

func TestCreateEventTeamStanding(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewEventTeamStandingWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating EventTeamStanding: %v", err)
	}
}

func TestCreateEvent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewEventWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Event: %v", err)
	}
}

func TestCreateEventWithBookingEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Events.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Events: %v", err)
	}

	if _, err := New().NewEventWithContext(ctx, EventMods.WithNewBookingEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Event with BookingEntries: %v", err)
	}

	after, err := models.Events.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Events: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Events to increase by 1, got %d", got)
	}
}

func TestCreateEventWithEventDriverStandingsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Events.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Events: %v", err)
	}

	if _, err := New().NewEventWithContext(ctx, EventMods.WithNewEventDriverStandings(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Event with EventDriverStandings: %v", err)
	}

	after, err := models.Events.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Events: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Events to increase by 1, got %d", got)
	}
}

func TestCreateEventWithEventProcessingAuditsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Events.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Events: %v", err)
	}

	if _, err := New().NewEventWithContext(ctx, EventMods.WithNewEventProcessingAudits(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Event with EventProcessingAudits: %v", err)
	}

	after, err := models.Events.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Events: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Events to increase by 1, got %d", got)
	}
}

func TestCreateEventWithEventTeamStandingsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Events.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Events: %v", err)
	}

	if _, err := New().NewEventWithContext(ctx, EventMods.WithNewEventTeamStandings(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Event with EventTeamStandings: %v", err)
	}

	after, err := models.Events.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Events: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Events to increase by 1, got %d", got)
	}
}

func TestCreateEventWithRacesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Events.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Events: %v", err)
	}

	if _, err := New().NewEventWithContext(ctx, EventMods.WithNewRaces(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Event with Races: %v", err)
	}

	after, err := models.Events.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Events: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Events to increase by 1, got %d", got)
	}
}

func TestCreateImportBatch(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewImportBatchWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating ImportBatch: %v", err)
	}
}

func TestCreateImportBatchWithEventProcessingAuditsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.ImportBatches.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting ImportBatches: %v", err)
	}

	if _, err := New().NewImportBatchWithContext(ctx, ImportBatchMods.WithNewEventProcessingAudits(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating ImportBatch with EventProcessingAudits: %v", err)
	}

	after, err := models.ImportBatches.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting ImportBatches: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected ImportBatches to increase by 1, got %d", got)
	}
}

func TestCreatePointRule(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewPointRuleWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating PointRule: %v", err)
	}
}

func TestCreatePointSystem(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewPointSystemWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating PointSystem: %v", err)
	}
}

func TestCreatePointSystemWithPointRulesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.PointSystems.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting PointSystems: %v", err)
	}

	if _, err := New().NewPointSystemWithContext(ctx, PointSystemMods.WithNewPointRules(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating PointSystem with PointRules: %v", err)
	}

	after, err := models.PointSystems.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting PointSystems: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected PointSystems to increase by 1, got %d", got)
	}
}

func TestCreatePointSystemWithSeasonsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.PointSystems.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting PointSystems: %v", err)
	}

	if _, err := New().NewPointSystemWithContext(ctx, PointSystemMods.WithNewSeasons(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating PointSystem with Seasons: %v", err)
	}

	after, err := models.PointSystems.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting PointSystems: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected PointSystems to increase by 1, got %d", got)
	}
}

func TestCreateRaceGrid(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewRaceGridWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating RaceGrid: %v", err)
	}
}

func TestCreateRaceGridWithBookingEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.RaceGrids.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RaceGrids: %v", err)
	}

	if _, err := New().NewRaceGridWithContext(ctx, RaceGridMods.WithNewBookingEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating RaceGrid with BookingEntries: %v", err)
	}

	after, err := models.RaceGrids.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RaceGrids: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected RaceGrids to increase by 1, got %d", got)
	}
}

func TestCreateRaceGridWithImportBatchesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.RaceGrids.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RaceGrids: %v", err)
	}

	if _, err := New().NewRaceGridWithContext(ctx, RaceGridMods.WithNewImportBatches(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating RaceGrid with ImportBatches: %v", err)
	}

	after, err := models.RaceGrids.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RaceGrids: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected RaceGrids to increase by 1, got %d", got)
	}
}

func TestCreateRaceGridWithResultEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.RaceGrids.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RaceGrids: %v", err)
	}

	if _, err := New().NewRaceGridWithContext(ctx, RaceGridMods.WithNewResultEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating RaceGrid with ResultEntries: %v", err)
	}

	after, err := models.RaceGrids.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RaceGrids: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected RaceGrids to increase by 1, got %d", got)
	}
}

func TestCreateRace(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewRaceWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Race: %v", err)
	}
}

func TestCreateRaceWithBookingEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Races.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Races: %v", err)
	}

	if _, err := New().NewRaceWithContext(ctx, RaceMods.WithNewBookingEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Race with BookingEntries: %v", err)
	}

	after, err := models.Races.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Races: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Races to increase by 1, got %d", got)
	}
}

func TestCreateRaceWithRaceGridsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Races.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Races: %v", err)
	}

	if _, err := New().NewRaceWithContext(ctx, RaceMods.WithNewRaceGrids(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Race with RaceGrids: %v", err)
	}

	after, err := models.Races.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Races: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Races to increase by 1, got %d", got)
	}
}

func TestCreateRacingSim(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewRacingSimWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating RacingSim: %v", err)
	}
}

func TestCreateRacingSimWithSimulationSeriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.RacingSims.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RacingSims: %v", err)
	}

	if _, err := New().NewRacingSimWithContext(ctx, RacingSimMods.WithNewSimulationSeries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating RacingSim with SimulationSeries: %v", err)
	}

	after, err := models.RacingSims.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RacingSims: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected RacingSims to increase by 1, got %d", got)
	}
}

func TestCreateRacingSimWithSimulationSimulationCarAliasesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.RacingSims.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RacingSims: %v", err)
	}

	if _, err := New().NewRacingSimWithContext(ctx, RacingSimMods.WithNewSimulationSimulationCarAliases(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating RacingSim with SimulationSimulationCarAliases: %v", err)
	}

	after, err := models.RacingSims.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RacingSims: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected RacingSims to increase by 1, got %d", got)
	}
}

func TestCreateRacingSimWithSimulationSimulationDriverAliasesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.RacingSims.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RacingSims: %v", err)
	}

	if _, err := New().NewRacingSimWithContext(ctx, RacingSimMods.WithNewSimulationSimulationDriverAliases(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating RacingSim with SimulationSimulationDriverAliases: %v", err)
	}

	after, err := models.RacingSims.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RacingSims: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected RacingSims to increase by 1, got %d", got)
	}
}

func TestCreateRacingSimWithSimulationSimulationTrackLayoutAliasesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.RacingSims.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RacingSims: %v", err)
	}

	if _, err := New().NewRacingSimWithContext(ctx, RacingSimMods.WithNewSimulationSimulationTrackLayoutAliases(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating RacingSim with SimulationSimulationTrackLayoutAliases: %v", err)
	}

	after, err := models.RacingSims.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting RacingSims: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected RacingSims to increase by 1, got %d", got)
	}
}

func TestCreateResultEntry(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewResultEntryWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating ResultEntry: %v", err)
	}
}

func TestCreateSeasonCarClass(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewSeasonCarClassWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating SeasonCarClass: %v", err)
	}
}

func TestCreateSeasonCarModel(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewSeasonCarModelWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating SeasonCarModel: %v", err)
	}
}

func TestCreateSeasonDriverStanding(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewSeasonDriverStandingWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating SeasonDriverStanding: %v", err)
	}
}

func TestCreateSeasonDriver(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewSeasonDriverWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating SeasonDriver: %v", err)
	}
}

func TestCreateSeasonTeamStanding(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewSeasonTeamStandingWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating SeasonTeamStanding: %v", err)
	}
}

func TestCreateSeason(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewSeasonWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Season: %v", err)
	}
}

func TestCreateSeasonWithEventDriverStandingsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if _, err := New().NewSeasonWithContext(ctx, SeasonMods.WithNewEventDriverStandings(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Season with EventDriverStandings: %v", err)
	}

	after, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Seasons to increase by 1, got %d", got)
	}
}

func TestCreateSeasonWithEventTeamStandingsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if _, err := New().NewSeasonWithContext(ctx, SeasonMods.WithNewEventTeamStandings(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Season with EventTeamStandings: %v", err)
	}

	after, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Seasons to increase by 1, got %d", got)
	}
}

func TestCreateSeasonWithEventsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if _, err := New().NewSeasonWithContext(ctx, SeasonMods.WithNewEvents(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Season with Events: %v", err)
	}

	after, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Seasons to increase by 1, got %d", got)
	}
}

func TestCreateSeasonWithSeasonCarClassesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if _, err := New().NewSeasonWithContext(ctx, SeasonMods.WithNewSeasonCarClasses(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Season with SeasonCarClasses: %v", err)
	}

	after, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Seasons to increase by 1, got %d", got)
	}
}

func TestCreateSeasonWithSeasonCarModelsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if _, err := New().NewSeasonWithContext(ctx, SeasonMods.WithNewSeasonCarModels(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Season with SeasonCarModels: %v", err)
	}

	after, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Seasons to increase by 1, got %d", got)
	}
}

func TestCreateSeasonWithSeasonDriverStandingsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if _, err := New().NewSeasonWithContext(ctx, SeasonMods.WithNewSeasonDriverStandings(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Season with SeasonDriverStandings: %v", err)
	}

	after, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Seasons to increase by 1, got %d", got)
	}
}

func TestCreateSeasonWithSeasonDriversDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if _, err := New().NewSeasonWithContext(ctx, SeasonMods.WithNewSeasonDrivers(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Season with SeasonDrivers: %v", err)
	}

	after, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Seasons to increase by 1, got %d", got)
	}
}

func TestCreateSeasonWithSeasonTeamStandingsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if _, err := New().NewSeasonWithContext(ctx, SeasonMods.WithNewSeasonTeamStandings(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Season with SeasonTeamStandings: %v", err)
	}

	after, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Seasons to increase by 1, got %d", got)
	}
}

func TestCreateSeasonWithTeamsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if _, err := New().NewSeasonWithContext(ctx, SeasonMods.WithNewTeams(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Season with Teams: %v", err)
	}

	after, err := models.Seasons.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Seasons: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Seasons to increase by 1, got %d", got)
	}
}

func TestCreateSeries(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewSeriesWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Series: %v", err)
	}
}

func TestCreateSeriesWithSeasonsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Serieses.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Serieses: %v", err)
	}

	if _, err := New().NewSeriesWithContext(ctx, SeriesMods.WithNewSeasons(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Series with Seasons: %v", err)
	}

	after, err := models.Serieses.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Serieses: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Serieses to increase by 1, got %d", got)
	}
}

func TestCreateSimulationCarAlias(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewSimulationCarAliasWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating SimulationCarAlias: %v", err)
	}
}

func TestCreateSimulationDriverAlias(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewSimulationDriverAliasWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating SimulationDriverAlias: %v", err)
	}
}

func TestCreateSimulationTrackLayoutAlias(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewSimulationTrackLayoutAliasWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating SimulationTrackLayoutAlias: %v", err)
	}
}

func TestCreateTeamDriver(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewTeamDriverWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating TeamDriver: %v", err)
	}
}

func TestCreateTeam(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewTeamWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Team: %v", err)
	}
}

func TestCreateTeamWithBookingEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Teams.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Teams: %v", err)
	}

	if _, err := New().NewTeamWithContext(ctx, TeamMods.WithNewBookingEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Team with BookingEntries: %v", err)
	}

	after, err := models.Teams.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Teams: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Teams to increase by 1, got %d", got)
	}
}

func TestCreateTeamWithEventTeamStandingsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Teams.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Teams: %v", err)
	}

	if _, err := New().NewTeamWithContext(ctx, TeamMods.WithNewEventTeamStandings(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Team with EventTeamStandings: %v", err)
	}

	after, err := models.Teams.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Teams: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Teams to increase by 1, got %d", got)
	}
}

func TestCreateTeamWithResultEntriesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Teams.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Teams: %v", err)
	}

	if _, err := New().NewTeamWithContext(ctx, TeamMods.WithNewResultEntries(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Team with ResultEntries: %v", err)
	}

	after, err := models.Teams.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Teams: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Teams to increase by 1, got %d", got)
	}
}

func TestCreateTeamWithSeasonTeamStandingsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Teams.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Teams: %v", err)
	}

	if _, err := New().NewTeamWithContext(ctx, TeamMods.WithNewSeasonTeamStandings(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Team with SeasonTeamStandings: %v", err)
	}

	after, err := models.Teams.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Teams: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Teams to increase by 1, got %d", got)
	}
}

func TestCreateTeamWithTeamDriversDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Teams.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Teams: %v", err)
	}

	if _, err := New().NewTeamWithContext(ctx, TeamMods.WithNewTeamDrivers(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Team with TeamDrivers: %v", err)
	}

	after, err := models.Teams.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Teams: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Teams to increase by 1, got %d", got)
	}
}

func TestCreateTrackLayout(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewTrackLayoutWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating TrackLayout: %v", err)
	}
}

func TestCreateTrackLayoutWithEventsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.TrackLayouts.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting TrackLayouts: %v", err)
	}

	if _, err := New().NewTrackLayoutWithContext(ctx, TrackLayoutMods.WithNewEvents(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating TrackLayout with Events: %v", err)
	}

	after, err := models.TrackLayouts.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting TrackLayouts: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected TrackLayouts to increase by 1, got %d", got)
	}
}

func TestCreateTrackLayoutWithSimulationTrackLayoutAliasesDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.TrackLayouts.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting TrackLayouts: %v", err)
	}

	if _, err := New().NewTrackLayoutWithContext(ctx, TrackLayoutMods.WithNewSimulationTrackLayoutAliases(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating TrackLayout with SimulationTrackLayoutAliases: %v", err)
	}

	after, err := models.TrackLayouts.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting TrackLayouts: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected TrackLayouts to increase by 1, got %d", got)
	}
}

func TestCreateTrack(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	if _, err := New().NewTrackWithContext(ctx).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Track: %v", err)
	}
}

func TestCreateTrackWithTrackLayoutsDoesNotDuplicateParent(t *testing.T) {
	if testDB == nil {
		t.Skip("skipping test, no DSN provided")
	}

	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)

	tx, err := testDB.Begin(ctx)
	if err != nil {
		t.Fatalf("Error starting transaction: %v", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			t.Fatalf("Error rolling back transaction: %v", err)
		}
	}()

	before, err := models.Tracks.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Tracks: %v", err)
	}

	if _, err := New().NewTrackWithContext(ctx, TrackMods.WithNewTrackLayouts(2)).Create(ctx, tx); err != nil {
		t.Fatalf("Error creating Track with TrackLayouts: %v", err)
	}

	after, err := models.Tracks.Query().Count(ctx, tx)
	if err != nil {
		t.Fatalf("Error counting Tracks: %v", err)
	}

	if got := after - before; got != 1 {
		t.Fatalf("Expected Tracks to increase by 1, got %d", got)
	}
}
