// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/srlmgr/backend/db/models"
	"github.com/stephenafamo/bob"
)

type DriverMod interface {
	Apply(context.Context, *DriverTemplate)
}

type DriverModFunc func(context.Context, *DriverTemplate)

func (f DriverModFunc) Apply(ctx context.Context, n *DriverTemplate) {
	f(ctx, n)
}

type DriverModSlice []DriverMod

func (mods DriverModSlice) Apply(ctx context.Context, n *DriverTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// DriverTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type DriverTemplate struct {
	ID               func() int32
	FrontendID       func() uuid.UUID
	ExternalID       func() string
	Name             func() string
	IsActive         func() bool
	LastImportedFrom func() null.Val[string]
	CreatedAt        func() time.Time
	UpdatedAt        func() time.Time
	CreatedBy        func() string
	UpdatedBy        func() string

	r driverR
	f *Factory

	alreadyPersisted bool
}

type driverR struct {
	BookingEntries        []*driverRBookingEntriesR
	DriverSimulationIds   []*driverRDriverSimulationIdsR
	EventDriverStandings  []*driverREventDriverStandingsR
	ResultEntries         []*driverRResultEntriesR
	SeasonDriverStandings []*driverRSeasonDriverStandingsR
	TeamDrivers           []*driverRTeamDriversR
}

type driverRBookingEntriesR struct {
	number int
	o      *BookingEntryTemplate
}
type driverRDriverSimulationIdsR struct {
	number int
	o      *DriverSimulationIDTemplate
}
type driverREventDriverStandingsR struct {
	number int
	o      *EventDriverStandingTemplate
}
type driverRResultEntriesR struct {
	number int
	o      *ResultEntryTemplate
}
type driverRSeasonDriverStandingsR struct {
	number int
	o      *SeasonDriverStandingTemplate
}
type driverRTeamDriversR struct {
	number int
	o      *TeamDriverTemplate
}

// Apply mods to the DriverTemplate
func (o *DriverTemplate) Apply(ctx context.Context, mods ...DriverMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Driver
// according to the relationships in the template. Nothing is inserted into the db
func (t DriverTemplate) setModelRels(o *models.Driver) {
	if t.r.BookingEntries != nil {
		rel := models.BookingEntrySlice{}
		for _, r := range t.r.BookingEntries {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.DriverID = null.From(o.ID) // h2
				rel.R.Driver = o
			}
			rel = append(rel, related...)
		}
		o.R.BookingEntries = rel
	}

	if t.r.DriverSimulationIds != nil {
		rel := models.DriverSimulationIDSlice{}
		for _, r := range t.r.DriverSimulationIds {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.DriverID = o.ID // h2
				rel.R.Driver = o
			}
			rel = append(rel, related...)
		}
		o.R.DriverSimulationIds = rel
	}

	if t.r.EventDriverStandings != nil {
		rel := models.EventDriverStandingSlice{}
		for _, r := range t.r.EventDriverStandings {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.DriverID = o.ID // h2
				rel.R.Driver = o
			}
			rel = append(rel, related...)
		}
		o.R.EventDriverStandings = rel
	}

	if t.r.ResultEntries != nil {
		rel := models.ResultEntrySlice{}
		for _, r := range t.r.ResultEntries {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.DriverID = null.From(o.ID) // h2
				rel.R.Driver = o
			}
			rel = append(rel, related...)
		}
		o.R.ResultEntries = rel
	}

	if t.r.SeasonDriverStandings != nil {
		rel := models.SeasonDriverStandingSlice{}
		for _, r := range t.r.SeasonDriverStandings {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.DriverID = o.ID // h2
				rel.R.Driver = o
			}
			rel = append(rel, related...)
		}
		o.R.SeasonDriverStandings = rel
	}

	if t.r.TeamDrivers != nil {
		rel := models.TeamDriverSlice{}
		for _, r := range t.r.TeamDrivers {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.DriverID = o.ID // h2
				rel.R.Driver = o
			}
			rel = append(rel, related...)
		}
		o.R.TeamDrivers = rel
	}
}

// BuildSetter returns an *models.DriverSetter
// this does nothing with the relationship templates
func (o DriverTemplate) BuildSetter() *models.DriverSetter {
	m := &models.DriverSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.FrontendID != nil {
		val := o.FrontendID()
		m.FrontendID = omit.From(val)
	}
	if o.ExternalID != nil {
		val := o.ExternalID()
		m.ExternalID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.IsActive != nil {
		val := o.IsActive()
		m.IsActive = omit.From(val)
	}
	if o.LastImportedFrom != nil {
		val := o.LastImportedFrom()
		m.LastImportedFrom = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}
	if o.CreatedBy != nil {
		val := o.CreatedBy()
		m.CreatedBy = omit.From(val)
	}
	if o.UpdatedBy != nil {
		val := o.UpdatedBy()
		m.UpdatedBy = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.DriverSetter
// this does nothing with the relationship templates
func (o DriverTemplate) BuildManySetter(number int) []*models.DriverSetter {
	m := make([]*models.DriverSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Driver
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use DriverTemplate.Create
func (o DriverTemplate) Build() *models.Driver {
	m := &models.Driver{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.FrontendID != nil {
		m.FrontendID = o.FrontendID()
	}
	if o.ExternalID != nil {
		m.ExternalID = o.ExternalID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.IsActive != nil {
		m.IsActive = o.IsActive()
	}
	if o.LastImportedFrom != nil {
		m.LastImportedFrom = o.LastImportedFrom()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.CreatedBy != nil {
		m.CreatedBy = o.CreatedBy()
	}
	if o.UpdatedBy != nil {
		m.UpdatedBy = o.UpdatedBy()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.DriverSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use DriverTemplate.CreateMany
func (o DriverTemplate) BuildMany(number int) models.DriverSlice {
	m := make(models.DriverSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableDriver(m *models.DriverSetter) {
	if !(m.ExternalID.IsValue()) {
		val := random_string(nil)
		m.ExternalID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Driver
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *DriverTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Driver) error {
	var err error

	isBookingEntriesDone, _ := driverRelBookingEntriesCtx.Value(ctx)
	if !isBookingEntriesDone && o.r.BookingEntries != nil {
		ctx = driverRelBookingEntriesCtx.WithValue(ctx, true)
		for _, r := range o.r.BookingEntries {
			if r.o.alreadyPersisted {
				m.R.BookingEntries = append(m.R.BookingEntries, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachBookingEntries(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isDriverSimulationIdsDone, _ := driverRelDriverSimulationIdsCtx.Value(ctx)
	if !isDriverSimulationIdsDone && o.r.DriverSimulationIds != nil {
		ctx = driverRelDriverSimulationIdsCtx.WithValue(ctx, true)
		for _, r := range o.r.DriverSimulationIds {
			if r.o.alreadyPersisted {
				m.R.DriverSimulationIds = append(m.R.DriverSimulationIds, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachDriverSimulationIds(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isEventDriverStandingsDone, _ := driverRelEventDriverStandingsCtx.Value(ctx)
	if !isEventDriverStandingsDone && o.r.EventDriverStandings != nil {
		ctx = driverRelEventDriverStandingsCtx.WithValue(ctx, true)
		for _, r := range o.r.EventDriverStandings {
			if r.o.alreadyPersisted {
				m.R.EventDriverStandings = append(m.R.EventDriverStandings, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachEventDriverStandings(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	isResultEntriesDone, _ := driverRelResultEntriesCtx.Value(ctx)
	if !isResultEntriesDone && o.r.ResultEntries != nil {
		ctx = driverRelResultEntriesCtx.WithValue(ctx, true)
		for _, r := range o.r.ResultEntries {
			if r.o.alreadyPersisted {
				m.R.ResultEntries = append(m.R.ResultEntries, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachResultEntries(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	isSeasonDriverStandingsDone, _ := driverRelSeasonDriverStandingsCtx.Value(ctx)
	if !isSeasonDriverStandingsDone && o.r.SeasonDriverStandings != nil {
		ctx = driverRelSeasonDriverStandingsCtx.WithValue(ctx, true)
		for _, r := range o.r.SeasonDriverStandings {
			if r.o.alreadyPersisted {
				m.R.SeasonDriverStandings = append(m.R.SeasonDriverStandings, r.o.Build())
			} else {
				rel4, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachSeasonDriverStandings(ctx, exec, rel4...)
				if err != nil {
					return err
				}
			}
		}
	}

	isTeamDriversDone, _ := driverRelTeamDriversCtx.Value(ctx)
	if !isTeamDriversDone && o.r.TeamDrivers != nil {
		ctx = driverRelTeamDriversCtx.WithValue(ctx, true)
		for _, r := range o.r.TeamDrivers {
			if r.o.alreadyPersisted {
				m.R.TeamDrivers = append(m.R.TeamDrivers, r.o.Build())
			} else {
				rel5, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachTeamDrivers(ctx, exec, rel5...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a driver and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *DriverTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Driver, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableDriver(opt)

	m, err := models.Drivers.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a driver and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *DriverTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Driver {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a driver and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *DriverTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Driver {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple drivers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o DriverTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.DriverSlice, error) {
	var err error
	m := make(models.DriverSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple drivers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o DriverTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.DriverSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple drivers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o DriverTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.DriverSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Driver has methods that act as mods for the DriverTemplate
var DriverMods driverMods

type driverMods struct{}

func (m driverMods) RandomizeAllColumns(f *faker.Faker) DriverMod {
	return DriverModSlice{
		DriverMods.RandomID(f),
		DriverMods.RandomFrontendID(f),
		DriverMods.RandomExternalID(f),
		DriverMods.RandomName(f),
		DriverMods.RandomIsActive(f),
		DriverMods.RandomLastImportedFrom(f),
		DriverMods.RandomCreatedAt(f),
		DriverMods.RandomUpdatedAt(f),
		DriverMods.RandomCreatedBy(f),
		DriverMods.RandomUpdatedBy(f),
	}
}

// Set the model columns to this value
func (m driverMods) ID(val int32) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m driverMods) IDFunc(f func() int32) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m driverMods) UnsetID() DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m driverMods) RandomID(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m driverMods) FrontendID(val uuid.UUID) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.FrontendID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m driverMods) FrontendIDFunc(f func() uuid.UUID) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.FrontendID = f
	})
}

// Clear any values for the column
func (m driverMods) UnsetFrontendID() DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.FrontendID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m driverMods) RandomFrontendID(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.FrontendID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m driverMods) ExternalID(val string) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.ExternalID = func() string { return val }
	})
}

// Set the Column from the function
func (m driverMods) ExternalIDFunc(f func() string) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.ExternalID = f
	})
}

// Clear any values for the column
func (m driverMods) UnsetExternalID() DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.ExternalID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m driverMods) RandomExternalID(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.ExternalID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m driverMods) Name(val string) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m driverMods) NameFunc(f func() string) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m driverMods) UnsetName() DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m driverMods) RandomName(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m driverMods) IsActive(val bool) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.IsActive = func() bool { return val }
	})
}

// Set the Column from the function
func (m driverMods) IsActiveFunc(f func() bool) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.IsActive = f
	})
}

// Clear any values for the column
func (m driverMods) UnsetIsActive() DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.IsActive = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m driverMods) RandomIsActive(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.IsActive = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m driverMods) LastImportedFrom(val null.Val[string]) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.LastImportedFrom = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m driverMods) LastImportedFromFunc(f func() null.Val[string]) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.LastImportedFrom = f
	})
}

// Clear any values for the column
func (m driverMods) UnsetLastImportedFrom() DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.LastImportedFrom = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m driverMods) RandomLastImportedFrom(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.LastImportedFrom = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m driverMods) RandomLastImportedFromNotNull(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.LastImportedFrom = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m driverMods) CreatedAt(val time.Time) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m driverMods) CreatedAtFunc(f func() time.Time) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m driverMods) UnsetCreatedAt() DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m driverMods) RandomCreatedAt(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m driverMods) UpdatedAt(val time.Time) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m driverMods) UpdatedAtFunc(f func() time.Time) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m driverMods) UnsetUpdatedAt() DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m driverMods) RandomUpdatedAt(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m driverMods) CreatedBy(val string) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.CreatedBy = func() string { return val }
	})
}

// Set the Column from the function
func (m driverMods) CreatedByFunc(f func() string) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.CreatedBy = f
	})
}

// Clear any values for the column
func (m driverMods) UnsetCreatedBy() DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.CreatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m driverMods) RandomCreatedBy(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.CreatedBy = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m driverMods) UpdatedBy(val string) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.UpdatedBy = func() string { return val }
	})
}

// Set the Column from the function
func (m driverMods) UpdatedByFunc(f func() string) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.UpdatedBy = f
	})
}

// Clear any values for the column
func (m driverMods) UnsetUpdatedBy() DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.UpdatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m driverMods) RandomUpdatedBy(f *faker.Faker) DriverMod {
	return DriverModFunc(func(_ context.Context, o *DriverTemplate) {
		o.UpdatedBy = func() string {
			return random_string(f)
		}
	})
}

func (m driverMods) WithParentsCascading() DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		if isDone, _ := driverWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = driverWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m driverMods) WithBookingEntries(number int, related *BookingEntryTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.BookingEntries = []*driverRBookingEntriesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m driverMods) WithNewBookingEntries(number int, mods ...BookingEntryMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewBookingEntryWithContext(ctx, mods...)
		m.WithBookingEntries(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddBookingEntries(number int, related *BookingEntryTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.BookingEntries = append(o.r.BookingEntries, &driverRBookingEntriesR{
			number: number,
			o:      related,
		})
	})
}

func (m driverMods) AddNewBookingEntries(number int, mods ...BookingEntryMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewBookingEntryWithContext(ctx, mods...)
		m.AddBookingEntries(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddExistingBookingEntries(existingModels ...*models.BookingEntry) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		for _, em := range existingModels {
			o.r.BookingEntries = append(o.r.BookingEntries, &driverRBookingEntriesR{
				o: o.f.FromExistingBookingEntry(em),
			})
		}
	})
}

func (m driverMods) WithoutBookingEntries() DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.BookingEntries = nil
	})
}

func (m driverMods) WithDriverSimulationIds(number int, related *DriverSimulationIDTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.DriverSimulationIds = []*driverRDriverSimulationIdsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m driverMods) WithNewDriverSimulationIds(number int, mods ...DriverSimulationIDMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewDriverSimulationIDWithContext(ctx, mods...)
		m.WithDriverSimulationIds(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddDriverSimulationIds(number int, related *DriverSimulationIDTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.DriverSimulationIds = append(o.r.DriverSimulationIds, &driverRDriverSimulationIdsR{
			number: number,
			o:      related,
		})
	})
}

func (m driverMods) AddNewDriverSimulationIds(number int, mods ...DriverSimulationIDMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewDriverSimulationIDWithContext(ctx, mods...)
		m.AddDriverSimulationIds(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddExistingDriverSimulationIds(existingModels ...*models.DriverSimulationID) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		for _, em := range existingModels {
			o.r.DriverSimulationIds = append(o.r.DriverSimulationIds, &driverRDriverSimulationIdsR{
				o: o.f.FromExistingDriverSimulationID(em),
			})
		}
	})
}

func (m driverMods) WithoutDriverSimulationIds() DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.DriverSimulationIds = nil
	})
}

func (m driverMods) WithEventDriverStandings(number int, related *EventDriverStandingTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.EventDriverStandings = []*driverREventDriverStandingsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m driverMods) WithNewEventDriverStandings(number int, mods ...EventDriverStandingMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewEventDriverStandingWithContext(ctx, mods...)
		m.WithEventDriverStandings(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddEventDriverStandings(number int, related *EventDriverStandingTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.EventDriverStandings = append(o.r.EventDriverStandings, &driverREventDriverStandingsR{
			number: number,
			o:      related,
		})
	})
}

func (m driverMods) AddNewEventDriverStandings(number int, mods ...EventDriverStandingMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewEventDriverStandingWithContext(ctx, mods...)
		m.AddEventDriverStandings(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddExistingEventDriverStandings(existingModels ...*models.EventDriverStanding) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		for _, em := range existingModels {
			o.r.EventDriverStandings = append(o.r.EventDriverStandings, &driverREventDriverStandingsR{
				o: o.f.FromExistingEventDriverStanding(em),
			})
		}
	})
}

func (m driverMods) WithoutEventDriverStandings() DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.EventDriverStandings = nil
	})
}

func (m driverMods) WithResultEntries(number int, related *ResultEntryTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.ResultEntries = []*driverRResultEntriesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m driverMods) WithNewResultEntries(number int, mods ...ResultEntryMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewResultEntryWithContext(ctx, mods...)
		m.WithResultEntries(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddResultEntries(number int, related *ResultEntryTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.ResultEntries = append(o.r.ResultEntries, &driverRResultEntriesR{
			number: number,
			o:      related,
		})
	})
}

func (m driverMods) AddNewResultEntries(number int, mods ...ResultEntryMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewResultEntryWithContext(ctx, mods...)
		m.AddResultEntries(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddExistingResultEntries(existingModels ...*models.ResultEntry) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		for _, em := range existingModels {
			o.r.ResultEntries = append(o.r.ResultEntries, &driverRResultEntriesR{
				o: o.f.FromExistingResultEntry(em),
			})
		}
	})
}

func (m driverMods) WithoutResultEntries() DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.ResultEntries = nil
	})
}

func (m driverMods) WithSeasonDriverStandings(number int, related *SeasonDriverStandingTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.SeasonDriverStandings = []*driverRSeasonDriverStandingsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m driverMods) WithNewSeasonDriverStandings(number int, mods ...SeasonDriverStandingMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewSeasonDriverStandingWithContext(ctx, mods...)
		m.WithSeasonDriverStandings(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddSeasonDriverStandings(number int, related *SeasonDriverStandingTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.SeasonDriverStandings = append(o.r.SeasonDriverStandings, &driverRSeasonDriverStandingsR{
			number: number,
			o:      related,
		})
	})
}

func (m driverMods) AddNewSeasonDriverStandings(number int, mods ...SeasonDriverStandingMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewSeasonDriverStandingWithContext(ctx, mods...)
		m.AddSeasonDriverStandings(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddExistingSeasonDriverStandings(existingModels ...*models.SeasonDriverStanding) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		for _, em := range existingModels {
			o.r.SeasonDriverStandings = append(o.r.SeasonDriverStandings, &driverRSeasonDriverStandingsR{
				o: o.f.FromExistingSeasonDriverStanding(em),
			})
		}
	})
}

func (m driverMods) WithoutSeasonDriverStandings() DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.SeasonDriverStandings = nil
	})
}

func (m driverMods) WithTeamDrivers(number int, related *TeamDriverTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.TeamDrivers = []*driverRTeamDriversR{{
			number: number,
			o:      related,
		}}
	})
}

func (m driverMods) WithNewTeamDrivers(number int, mods ...TeamDriverMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewTeamDriverWithContext(ctx, mods...)
		m.WithTeamDrivers(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddTeamDrivers(number int, related *TeamDriverTemplate) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.TeamDrivers = append(o.r.TeamDrivers, &driverRTeamDriversR{
			number: number,
			o:      related,
		})
	})
}

func (m driverMods) AddNewTeamDrivers(number int, mods ...TeamDriverMod) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		related := o.f.NewTeamDriverWithContext(ctx, mods...)
		m.AddTeamDrivers(number, related).Apply(ctx, o)
	})
}

func (m driverMods) AddExistingTeamDrivers(existingModels ...*models.TeamDriver) DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		for _, em := range existingModels {
			o.r.TeamDrivers = append(o.r.TeamDrivers, &driverRTeamDriversR{
				o: o.f.FromExistingTeamDriver(em),
			})
		}
	})
}

func (m driverMods) WithoutTeamDrivers() DriverMod {
	return DriverModFunc(func(ctx context.Context, o *DriverTemplate) {
		o.r.TeamDrivers = nil
	})
}
