// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/srlmgr/backend/db/models"
	mytypes "github.com/srlmgr/backend/db/mytypes"
	"github.com/stephenafamo/bob"
)

type ImportBatchMod interface {
	Apply(context.Context, *ImportBatchTemplate)
}

type ImportBatchModFunc func(context.Context, *ImportBatchTemplate)

func (f ImportBatchModFunc) Apply(ctx context.Context, n *ImportBatchTemplate) {
	f(ctx, n)
}

type ImportBatchModSlice []ImportBatchMod

func (mods ImportBatchModSlice) Apply(ctx context.Context, n *ImportBatchTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ImportBatchTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ImportBatchTemplate struct {
	ID              func() int32
	FrontendID      func() uuid.UUID
	RaceGridID      func() int32
	ImportFormat    func() mytypes.ImportFormat
	Payload         func() []byte
	SourceFilename  func() null.Val[string]
	ProcessingState func() string
	MetadataJSON    func() mytypes.ImportBatchMeta
	ProcessedAt     func() null.Val[time.Time]
	CreatedAt       func() time.Time
	UpdatedAt       func() time.Time
	CreatedBy       func() string
	UpdatedBy       func() string

	r importBatchR
	f *Factory

	alreadyPersisted bool
}

type importBatchR struct {
	EventProcessingAudits []*importBatchREventProcessingAuditsR
	RaceGrid              *importBatchRRaceGridR
}

type importBatchREventProcessingAuditsR struct {
	number int
	o      *EventProcessingAuditTemplate
}
type importBatchRRaceGridR struct {
	o *RaceGridTemplate
}

// Apply mods to the ImportBatchTemplate
func (o *ImportBatchTemplate) Apply(ctx context.Context, mods ...ImportBatchMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ImportBatch
// according to the relationships in the template. Nothing is inserted into the db
func (t ImportBatchTemplate) setModelRels(o *models.ImportBatch) {
	if t.r.EventProcessingAudits != nil {
		rel := models.EventProcessingAuditSlice{}
		for _, r := range t.r.EventProcessingAudits {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ImportBatchID = null.From(o.ID) // h2
				rel.R.ImportBatch = o
			}
			rel = append(rel, related...)
		}
		o.R.EventProcessingAudits = rel
	}

	if t.r.RaceGrid != nil {
		rel := t.r.RaceGrid.o.Build()
		rel.R.ImportBatches = append(rel.R.ImportBatches, o)
		o.RaceGridID = rel.ID // h2
		o.R.RaceGrid = rel
	}
}

// BuildSetter returns an *models.ImportBatchSetter
// this does nothing with the relationship templates
func (o ImportBatchTemplate) BuildSetter() *models.ImportBatchSetter {
	m := &models.ImportBatchSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.FrontendID != nil {
		val := o.FrontendID()
		m.FrontendID = omit.From(val)
	}
	if o.RaceGridID != nil {
		val := o.RaceGridID()
		m.RaceGridID = omit.From(val)
	}
	if o.ImportFormat != nil {
		val := o.ImportFormat()
		m.ImportFormat = omit.From(val)
	}
	if o.Payload != nil {
		val := o.Payload()
		m.Payload = omit.From(val)
	}
	if o.SourceFilename != nil {
		val := o.SourceFilename()
		m.SourceFilename = omitnull.FromNull(val)
	}
	if o.ProcessingState != nil {
		val := o.ProcessingState()
		m.ProcessingState = omit.From(val)
	}
	if o.MetadataJSON != nil {
		val := o.MetadataJSON()
		m.MetadataJSON = omit.From(val)
	}
	if o.ProcessedAt != nil {
		val := o.ProcessedAt()
		m.ProcessedAt = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}
	if o.CreatedBy != nil {
		val := o.CreatedBy()
		m.CreatedBy = omit.From(val)
	}
	if o.UpdatedBy != nil {
		val := o.UpdatedBy()
		m.UpdatedBy = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ImportBatchSetter
// this does nothing with the relationship templates
func (o ImportBatchTemplate) BuildManySetter(number int) []*models.ImportBatchSetter {
	m := make([]*models.ImportBatchSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ImportBatch
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ImportBatchTemplate.Create
func (o ImportBatchTemplate) Build() *models.ImportBatch {
	m := &models.ImportBatch{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.FrontendID != nil {
		m.FrontendID = o.FrontendID()
	}
	if o.RaceGridID != nil {
		m.RaceGridID = o.RaceGridID()
	}
	if o.ImportFormat != nil {
		m.ImportFormat = o.ImportFormat()
	}
	if o.Payload != nil {
		m.Payload = o.Payload()
	}
	if o.SourceFilename != nil {
		m.SourceFilename = o.SourceFilename()
	}
	if o.ProcessingState != nil {
		m.ProcessingState = o.ProcessingState()
	}
	if o.MetadataJSON != nil {
		m.MetadataJSON = o.MetadataJSON()
	}
	if o.ProcessedAt != nil {
		m.ProcessedAt = o.ProcessedAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.CreatedBy != nil {
		m.CreatedBy = o.CreatedBy()
	}
	if o.UpdatedBy != nil {
		m.UpdatedBy = o.UpdatedBy()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ImportBatchSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ImportBatchTemplate.CreateMany
func (o ImportBatchTemplate) BuildMany(number int) models.ImportBatchSlice {
	m := make(models.ImportBatchSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableImportBatch(m *models.ImportBatchSetter) {
	if !(m.RaceGridID.IsValue()) {
		val := random_int32(nil)
		m.RaceGridID = omit.From(val)
	}
	if !(m.ImportFormat.IsValue()) {
		val := random_mytypes_ImportFormat(nil)
		m.ImportFormat = omit.From(val)
	}
	if !(m.Payload.IsValue()) {
		val := random___byte(nil)
		m.Payload = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ImportBatch
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ImportBatchTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ImportBatch) error {
	var err error

	isEventProcessingAuditsDone, _ := importBatchRelEventProcessingAuditsCtx.Value(ctx)
	if !isEventProcessingAuditsDone && o.r.EventProcessingAudits != nil {
		ctx = importBatchRelEventProcessingAuditsCtx.WithValue(ctx, true)
		for _, r := range o.r.EventProcessingAudits {
			if r.o.alreadyPersisted {
				m.R.EventProcessingAudits = append(m.R.EventProcessingAudits, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachEventProcessingAudits(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a importBatch and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ImportBatchTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ImportBatch, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableImportBatch(opt)

	if o.r.RaceGrid == nil {
		ImportBatchMods.WithNewRaceGrid().Apply(ctx, o)
	}

	var rel1 *models.RaceGrid

	if o.r.RaceGrid.o.alreadyPersisted {
		rel1 = o.r.RaceGrid.o.Build()
	} else {
		rel1, err = o.r.RaceGrid.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.RaceGridID = omit.From(rel1.ID)

	m, err := models.ImportBatches.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.RaceGrid = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a importBatch and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ImportBatchTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ImportBatch {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a importBatch and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ImportBatchTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ImportBatch {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple importBatches and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ImportBatchTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ImportBatchSlice, error) {
	var err error
	m := make(models.ImportBatchSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple importBatches and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ImportBatchTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ImportBatchSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple importBatches and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ImportBatchTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ImportBatchSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ImportBatch has methods that act as mods for the ImportBatchTemplate
var ImportBatchMods importBatchMods

type importBatchMods struct{}

func (m importBatchMods) RandomizeAllColumns(f *faker.Faker) ImportBatchMod {
	return ImportBatchModSlice{
		ImportBatchMods.RandomID(f),
		ImportBatchMods.RandomFrontendID(f),
		ImportBatchMods.RandomRaceGridID(f),
		ImportBatchMods.RandomImportFormat(f),
		ImportBatchMods.RandomPayload(f),
		ImportBatchMods.RandomSourceFilename(f),
		ImportBatchMods.RandomProcessingState(f),
		ImportBatchMods.RandomMetadataJSON(f),
		ImportBatchMods.RandomProcessedAt(f),
		ImportBatchMods.RandomCreatedAt(f),
		ImportBatchMods.RandomUpdatedAt(f),
		ImportBatchMods.RandomCreatedBy(f),
		ImportBatchMods.RandomUpdatedBy(f),
	}
}

// Set the model columns to this value
func (m importBatchMods) ID(val int32) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) IDFunc(f func() int32) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetID() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomID(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) FrontendID(val uuid.UUID) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.FrontendID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) FrontendIDFunc(f func() uuid.UUID) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.FrontendID = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetFrontendID() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.FrontendID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomFrontendID(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.FrontendID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) RaceGridID(val int32) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.RaceGridID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) RaceGridIDFunc(f func() int32) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.RaceGridID = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetRaceGridID() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.RaceGridID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomRaceGridID(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.RaceGridID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) ImportFormat(val mytypes.ImportFormat) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ImportFormat = func() mytypes.ImportFormat { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) ImportFormatFunc(f func() mytypes.ImportFormat) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ImportFormat = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetImportFormat() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ImportFormat = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomImportFormat(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ImportFormat = func() mytypes.ImportFormat {
			return random_mytypes_ImportFormat(f)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) Payload(val []byte) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.Payload = func() []byte { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) PayloadFunc(f func() []byte) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.Payload = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetPayload() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.Payload = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomPayload(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.Payload = func() []byte {
			return random___byte(f)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) SourceFilename(val null.Val[string]) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.SourceFilename = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) SourceFilenameFunc(f func() null.Val[string]) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.SourceFilename = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetSourceFilename() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.SourceFilename = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m importBatchMods) RandomSourceFilename(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.SourceFilename = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m importBatchMods) RandomSourceFilenameNotNull(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.SourceFilename = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) ProcessingState(val string) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ProcessingState = func() string { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) ProcessingStateFunc(f func() string) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ProcessingState = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetProcessingState() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ProcessingState = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomProcessingState(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ProcessingState = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) MetadataJSON(val mytypes.ImportBatchMeta) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.MetadataJSON = func() mytypes.ImportBatchMeta { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) MetadataJSONFunc(f func() mytypes.ImportBatchMeta) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.MetadataJSON = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetMetadataJSON() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.MetadataJSON = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomMetadataJSON(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.MetadataJSON = func() mytypes.ImportBatchMeta {
			return random_mytypes_ImportBatchMeta(f)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) ProcessedAt(val null.Val[time.Time]) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ProcessedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) ProcessedAtFunc(f func() null.Val[time.Time]) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ProcessedAt = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetProcessedAt() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ProcessedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m importBatchMods) RandomProcessedAt(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ProcessedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m importBatchMods) RandomProcessedAtNotNull(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.ProcessedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) CreatedAt(val time.Time) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) CreatedAtFunc(f func() time.Time) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetCreatedAt() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomCreatedAt(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) UpdatedAt(val time.Time) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) UpdatedAtFunc(f func() time.Time) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetUpdatedAt() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomUpdatedAt(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) CreatedBy(val string) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.CreatedBy = func() string { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) CreatedByFunc(f func() string) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.CreatedBy = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetCreatedBy() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.CreatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomCreatedBy(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.CreatedBy = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m importBatchMods) UpdatedBy(val string) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.UpdatedBy = func() string { return val }
	})
}

// Set the Column from the function
func (m importBatchMods) UpdatedByFunc(f func() string) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.UpdatedBy = f
	})
}

// Clear any values for the column
func (m importBatchMods) UnsetUpdatedBy() ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.UpdatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m importBatchMods) RandomUpdatedBy(f *faker.Faker) ImportBatchMod {
	return ImportBatchModFunc(func(_ context.Context, o *ImportBatchTemplate) {
		o.UpdatedBy = func() string {
			return random_string(f)
		}
	})
}

func (m importBatchMods) WithParentsCascading() ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		if isDone, _ := importBatchWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = importBatchWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewRaceGridWithContext(ctx, RaceGridMods.WithParentsCascading())
			m.WithRaceGrid(related).Apply(ctx, o)
		}
	})
}

func (m importBatchMods) WithRaceGrid(rel *RaceGridTemplate) ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		o.r.RaceGrid = &importBatchRRaceGridR{
			o: rel,
		}
	})
}

func (m importBatchMods) WithNewRaceGrid(mods ...RaceGridMod) ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		related := o.f.NewRaceGridWithContext(ctx, mods...)

		m.WithRaceGrid(related).Apply(ctx, o)
	})
}

func (m importBatchMods) WithExistingRaceGrid(em *models.RaceGrid) ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		o.r.RaceGrid = &importBatchRRaceGridR{
			o: o.f.FromExistingRaceGrid(em),
		}
	})
}

func (m importBatchMods) WithoutRaceGrid() ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		o.r.RaceGrid = nil
	})
}

func (m importBatchMods) WithEventProcessingAudits(number int, related *EventProcessingAuditTemplate) ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		o.r.EventProcessingAudits = []*importBatchREventProcessingAuditsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m importBatchMods) WithNewEventProcessingAudits(number int, mods ...EventProcessingAuditMod) ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		related := o.f.NewEventProcessingAuditWithContext(ctx, mods...)
		m.WithEventProcessingAudits(number, related).Apply(ctx, o)
	})
}

func (m importBatchMods) AddEventProcessingAudits(number int, related *EventProcessingAuditTemplate) ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		o.r.EventProcessingAudits = append(o.r.EventProcessingAudits, &importBatchREventProcessingAuditsR{
			number: number,
			o:      related,
		})
	})
}

func (m importBatchMods) AddNewEventProcessingAudits(number int, mods ...EventProcessingAuditMod) ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		related := o.f.NewEventProcessingAuditWithContext(ctx, mods...)
		m.AddEventProcessingAudits(number, related).Apply(ctx, o)
	})
}

func (m importBatchMods) AddExistingEventProcessingAudits(existingModels ...*models.EventProcessingAudit) ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		for _, em := range existingModels {
			o.r.EventProcessingAudits = append(o.r.EventProcessingAudits, &importBatchREventProcessingAuditsR{
				o: o.f.FromExistingEventProcessingAudit(em),
			})
		}
	})
}

func (m importBatchMods) WithoutEventProcessingAudits() ImportBatchMod {
	return ImportBatchModFunc(func(ctx context.Context, o *ImportBatchTemplate) {
		o.r.EventProcessingAudits = nil
	})
}
