// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	models "github.com/srlmgr/backend/db/models"
	"github.com/stephenafamo/bob"
)

type SeasonMod interface {
	Apply(context.Context, *SeasonTemplate)
}

type SeasonModFunc func(context.Context, *SeasonTemplate)

func (f SeasonModFunc) Apply(ctx context.Context, n *SeasonTemplate) {
	f(ctx, n)
}

type SeasonModSlice []SeasonMod

func (mods SeasonModSlice) Apply(ctx context.Context, n *SeasonTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// SeasonTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type SeasonTemplate struct {
	ID            func() int32
	SeriesID      func() int32
	PointSystemID func() int32
	Name          func() string
	ShortName     func() string
	StartsAt      func() null.Val[time.Time]
	EndsAt        func() null.Val[time.Time]
	Status        func() string
	IsActive      func() bool
	CreatedAt     func() time.Time
	UpdatedAt     func() time.Time
	CreatedBy     func() string
	UpdatedBy     func() string

	r seasonR
	f *Factory

	alreadyPersisted bool
}

type seasonR struct {
	Events      []*seasonREventsR
	PointSystem *seasonRPointSystemR
	Series      *seasonRSeriesR
	Teams       []*seasonRTeamsR
}

type seasonREventsR struct {
	number int
	o      *EventTemplate
}
type seasonRPointSystemR struct {
	o *PointSystemTemplate
}
type seasonRSeriesR struct {
	o *SeriesTemplate
}
type seasonRTeamsR struct {
	number int
	o      *TeamTemplate
}

// Apply mods to the SeasonTemplate
func (o *SeasonTemplate) Apply(ctx context.Context, mods ...SeasonMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Season
// according to the relationships in the template. Nothing is inserted into the db
func (t SeasonTemplate) setModelRels(o *models.Season) {
	if t.r.Events != nil {
		rel := models.EventSlice{}
		for _, r := range t.r.Events {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.SeasonID = o.ID // h2
				rel.R.Season = o
			}
			rel = append(rel, related...)
		}
		o.R.Events = rel
	}

	if t.r.PointSystem != nil {
		rel := t.r.PointSystem.o.Build()
		rel.R.Seasons = append(rel.R.Seasons, o)
		o.PointSystemID = rel.ID // h2
		o.R.PointSystem = rel
	}

	if t.r.Series != nil {
		rel := t.r.Series.o.Build()
		rel.R.Seasons = append(rel.R.Seasons, o)
		o.SeriesID = rel.ID // h2
		o.R.Series = rel
	}

	if t.r.Teams != nil {
		rel := models.TeamSlice{}
		for _, r := range t.r.Teams {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.SeasonID = o.ID // h2
				rel.R.Season = o
			}
			rel = append(rel, related...)
		}
		o.R.Teams = rel
	}
}

// BuildSetter returns an *models.SeasonSetter
// this does nothing with the relationship templates
func (o SeasonTemplate) BuildSetter() *models.SeasonSetter {
	m := &models.SeasonSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.SeriesID != nil {
		val := o.SeriesID()
		m.SeriesID = omit.From(val)
	}
	if o.PointSystemID != nil {
		val := o.PointSystemID()
		m.PointSystemID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.ShortName != nil {
		val := o.ShortName()
		m.ShortName = omit.From(val)
	}
	if o.StartsAt != nil {
		val := o.StartsAt()
		m.StartsAt = omitnull.FromNull(val)
	}
	if o.EndsAt != nil {
		val := o.EndsAt()
		m.EndsAt = omitnull.FromNull(val)
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = omit.From(val)
	}
	if o.IsActive != nil {
		val := o.IsActive()
		m.IsActive = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}
	if o.CreatedBy != nil {
		val := o.CreatedBy()
		m.CreatedBy = omit.From(val)
	}
	if o.UpdatedBy != nil {
		val := o.UpdatedBy()
		m.UpdatedBy = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.SeasonSetter
// this does nothing with the relationship templates
func (o SeasonTemplate) BuildManySetter(number int) []*models.SeasonSetter {
	m := make([]*models.SeasonSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Season
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SeasonTemplate.Create
func (o SeasonTemplate) Build() *models.Season {
	m := &models.Season{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.SeriesID != nil {
		m.SeriesID = o.SeriesID()
	}
	if o.PointSystemID != nil {
		m.PointSystemID = o.PointSystemID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.ShortName != nil {
		m.ShortName = o.ShortName()
	}
	if o.StartsAt != nil {
		m.StartsAt = o.StartsAt()
	}
	if o.EndsAt != nil {
		m.EndsAt = o.EndsAt()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.IsActive != nil {
		m.IsActive = o.IsActive()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.CreatedBy != nil {
		m.CreatedBy = o.CreatedBy()
	}
	if o.UpdatedBy != nil {
		m.UpdatedBy = o.UpdatedBy()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.SeasonSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SeasonTemplate.CreateMany
func (o SeasonTemplate) BuildMany(number int) models.SeasonSlice {
	m := make(models.SeasonSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableSeason(m *models.SeasonSetter) {
	if !(m.SeriesID.IsValue()) {
		val := random_int32(nil)
		m.SeriesID = omit.From(val)
	}
	if !(m.PointSystemID.IsValue()) {
		val := random_int32(nil)
		m.PointSystemID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
	if !(m.ShortName.IsValue()) {
		val := random_string(nil)
		m.ShortName = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Season
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *SeasonTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Season) error {
	var err error

	isEventsDone, _ := seasonRelEventsCtx.Value(ctx)
	if !isEventsDone && o.r.Events != nil {
		ctx = seasonRelEventsCtx.WithValue(ctx, true)
		for _, r := range o.r.Events {
			if r.o.alreadyPersisted {
				m.R.Events = append(m.R.Events, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachEvents(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isTeamsDone, _ := seasonRelTeamsCtx.Value(ctx)
	if !isTeamsDone && o.r.Teams != nil {
		ctx = seasonRelTeamsCtx.WithValue(ctx, true)
		for _, r := range o.r.Teams {
			if r.o.alreadyPersisted {
				m.R.Teams = append(m.R.Teams, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachTeams(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a season and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *SeasonTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Season, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableSeason(opt)

	if o.r.PointSystem == nil {
		SeasonMods.WithNewPointSystem().Apply(ctx, o)
	}

	var rel1 *models.PointSystem

	if o.r.PointSystem.o.alreadyPersisted {
		rel1 = o.r.PointSystem.o.Build()
	} else {
		rel1, err = o.r.PointSystem.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.PointSystemID = omit.From(rel1.ID)

	if o.r.Series == nil {
		SeasonMods.WithNewSeries().Apply(ctx, o)
	}

	var rel2 *models.Series

	if o.r.Series.o.alreadyPersisted {
		rel2 = o.r.Series.o.Build()
	} else {
		rel2, err = o.r.Series.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.SeriesID = omit.From(rel2.ID)

	m, err := models.Seasons.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.PointSystem = rel1
	m.R.Series = rel2

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a season and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *SeasonTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Season {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a season and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *SeasonTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Season {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple seasons and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o SeasonTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.SeasonSlice, error) {
	var err error
	m := make(models.SeasonSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple seasons and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o SeasonTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.SeasonSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple seasons and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o SeasonTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.SeasonSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Season has methods that act as mods for the SeasonTemplate
var SeasonMods seasonMods

type seasonMods struct{}

func (m seasonMods) RandomizeAllColumns(f *faker.Faker) SeasonMod {
	return SeasonModSlice{
		SeasonMods.RandomID(f),
		SeasonMods.RandomSeriesID(f),
		SeasonMods.RandomPointSystemID(f),
		SeasonMods.RandomName(f),
		SeasonMods.RandomShortName(f),
		SeasonMods.RandomStartsAt(f),
		SeasonMods.RandomEndsAt(f),
		SeasonMods.RandomStatus(f),
		SeasonMods.RandomIsActive(f),
		SeasonMods.RandomCreatedAt(f),
		SeasonMods.RandomUpdatedAt(f),
		SeasonMods.RandomCreatedBy(f),
		SeasonMods.RandomUpdatedBy(f),
	}
}

// Set the model columns to this value
func (m seasonMods) ID(val int32) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m seasonMods) IDFunc(f func() int32) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetID() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomID(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) SeriesID(val int32) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.SeriesID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m seasonMods) SeriesIDFunc(f func() int32) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.SeriesID = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetSeriesID() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.SeriesID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomSeriesID(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.SeriesID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) PointSystemID(val int32) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.PointSystemID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m seasonMods) PointSystemIDFunc(f func() int32) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.PointSystemID = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetPointSystemID() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.PointSystemID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomPointSystemID(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.PointSystemID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) Name(val string) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m seasonMods) NameFunc(f func() string) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetName() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomName(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) ShortName(val string) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.ShortName = func() string { return val }
	})
}

// Set the Column from the function
func (m seasonMods) ShortNameFunc(f func() string) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.ShortName = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetShortName() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.ShortName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomShortName(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.ShortName = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) StartsAt(val null.Val[time.Time]) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.StartsAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m seasonMods) StartsAtFunc(f func() null.Val[time.Time]) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.StartsAt = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetStartsAt() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.StartsAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m seasonMods) RandomStartsAt(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.StartsAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m seasonMods) RandomStartsAtNotNull(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.StartsAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) EndsAt(val null.Val[time.Time]) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.EndsAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m seasonMods) EndsAtFunc(f func() null.Val[time.Time]) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.EndsAt = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetEndsAt() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.EndsAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m seasonMods) RandomEndsAt(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.EndsAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m seasonMods) RandomEndsAtNotNull(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.EndsAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) Status(val string) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m seasonMods) StatusFunc(f func() string) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetStatus() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomStatus(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.Status = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) IsActive(val bool) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.IsActive = func() bool { return val }
	})
}

// Set the Column from the function
func (m seasonMods) IsActiveFunc(f func() bool) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.IsActive = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetIsActive() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.IsActive = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomIsActive(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.IsActive = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) CreatedAt(val time.Time) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m seasonMods) CreatedAtFunc(f func() time.Time) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetCreatedAt() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomCreatedAt(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) UpdatedAt(val time.Time) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m seasonMods) UpdatedAtFunc(f func() time.Time) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetUpdatedAt() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomUpdatedAt(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) CreatedBy(val string) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.CreatedBy = func() string { return val }
	})
}

// Set the Column from the function
func (m seasonMods) CreatedByFunc(f func() string) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.CreatedBy = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetCreatedBy() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.CreatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomCreatedBy(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.CreatedBy = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m seasonMods) UpdatedBy(val string) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.UpdatedBy = func() string { return val }
	})
}

// Set the Column from the function
func (m seasonMods) UpdatedByFunc(f func() string) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.UpdatedBy = f
	})
}

// Clear any values for the column
func (m seasonMods) UnsetUpdatedBy() SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.UpdatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seasonMods) RandomUpdatedBy(f *faker.Faker) SeasonMod {
	return SeasonModFunc(func(_ context.Context, o *SeasonTemplate) {
		o.UpdatedBy = func() string {
			return random_string(f)
		}
	})
}

func (m seasonMods) WithParentsCascading() SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		if isDone, _ := seasonWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = seasonWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewPointSystemWithContext(ctx, PointSystemMods.WithParentsCascading())
			m.WithPointSystem(related).Apply(ctx, o)
		}
		{

			related := o.f.NewSeriesWithContext(ctx, SeriesMods.WithParentsCascading())
			m.WithSeries(related).Apply(ctx, o)
		}
	})
}

func (m seasonMods) WithPointSystem(rel *PointSystemTemplate) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.PointSystem = &seasonRPointSystemR{
			o: rel,
		}
	})
}

func (m seasonMods) WithNewPointSystem(mods ...PointSystemMod) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		related := o.f.NewPointSystemWithContext(ctx, mods...)

		m.WithPointSystem(related).Apply(ctx, o)
	})
}

func (m seasonMods) WithExistingPointSystem(em *models.PointSystem) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.PointSystem = &seasonRPointSystemR{
			o: o.f.FromExistingPointSystem(em),
		}
	})
}

func (m seasonMods) WithoutPointSystem() SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.PointSystem = nil
	})
}

func (m seasonMods) WithSeries(rel *SeriesTemplate) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.Series = &seasonRSeriesR{
			o: rel,
		}
	})
}

func (m seasonMods) WithNewSeries(mods ...SeriesMod) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		related := o.f.NewSeriesWithContext(ctx, mods...)

		m.WithSeries(related).Apply(ctx, o)
	})
}

func (m seasonMods) WithExistingSeries(em *models.Series) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.Series = &seasonRSeriesR{
			o: o.f.FromExistingSeries(em),
		}
	})
}

func (m seasonMods) WithoutSeries() SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.Series = nil
	})
}

func (m seasonMods) WithEvents(number int, related *EventTemplate) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.Events = []*seasonREventsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m seasonMods) WithNewEvents(number int, mods ...EventMod) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		related := o.f.NewEventWithContext(ctx, mods...)
		m.WithEvents(number, related).Apply(ctx, o)
	})
}

func (m seasonMods) AddEvents(number int, related *EventTemplate) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.Events = append(o.r.Events, &seasonREventsR{
			number: number,
			o:      related,
		})
	})
}

func (m seasonMods) AddNewEvents(number int, mods ...EventMod) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		related := o.f.NewEventWithContext(ctx, mods...)
		m.AddEvents(number, related).Apply(ctx, o)
	})
}

func (m seasonMods) AddExistingEvents(existingModels ...*models.Event) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		for _, em := range existingModels {
			o.r.Events = append(o.r.Events, &seasonREventsR{
				o: o.f.FromExistingEvent(em),
			})
		}
	})
}

func (m seasonMods) WithoutEvents() SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.Events = nil
	})
}

func (m seasonMods) WithTeams(number int, related *TeamTemplate) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.Teams = []*seasonRTeamsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m seasonMods) WithNewTeams(number int, mods ...TeamMod) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		related := o.f.NewTeamWithContext(ctx, mods...)
		m.WithTeams(number, related).Apply(ctx, o)
	})
}

func (m seasonMods) AddTeams(number int, related *TeamTemplate) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.Teams = append(o.r.Teams, &seasonRTeamsR{
			number: number,
			o:      related,
		})
	})
}

func (m seasonMods) AddNewTeams(number int, mods ...TeamMod) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		related := o.f.NewTeamWithContext(ctx, mods...)
		m.AddTeams(number, related).Apply(ctx, o)
	})
}

func (m seasonMods) AddExistingTeams(existingModels ...*models.Team) SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		for _, em := range existingModels {
			o.r.Teams = append(o.r.Teams, &seasonRTeamsR{
				o: o.f.FromExistingTeam(em),
			})
		}
	})
}

func (m seasonMods) WithoutTeams() SeasonMod {
	return SeasonModFunc(func(ctx context.Context, o *SeasonTemplate) {
		o.r.Teams = nil
	})
}
