// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	models "github.com/srlmgr/backend/db/models"
	"github.com/stephenafamo/bob"
)

type SimulationTrackLayoutAliasMod interface {
	Apply(context.Context, *SimulationTrackLayoutAliasTemplate)
}

type SimulationTrackLayoutAliasModFunc func(context.Context, *SimulationTrackLayoutAliasTemplate)

func (f SimulationTrackLayoutAliasModFunc) Apply(ctx context.Context, n *SimulationTrackLayoutAliasTemplate) {
	f(ctx, n)
}

type SimulationTrackLayoutAliasModSlice []SimulationTrackLayoutAliasMod

func (mods SimulationTrackLayoutAliasModSlice) Apply(ctx context.Context, n *SimulationTrackLayoutAliasTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// SimulationTrackLayoutAliasTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type SimulationTrackLayoutAliasTemplate struct {
	ID            func() int32
	TrackLayoutID func() int32
	SimulationID  func() int32
	ExternalName  func() string
	CreatedAt     func() time.Time
	UpdatedAt     func() time.Time
	CreatedBy     func() string
	UpdatedBy     func() string

	r simulationTrackLayoutAliasR
	f *Factory

	alreadyPersisted bool
}

type simulationTrackLayoutAliasR struct {
	SimulationRacingSim *simulationTrackLayoutAliasRSimulationRacingSimR
	TrackLayout         *simulationTrackLayoutAliasRTrackLayoutR
}

type simulationTrackLayoutAliasRSimulationRacingSimR struct {
	o *RacingSimTemplate
}
type simulationTrackLayoutAliasRTrackLayoutR struct {
	o *TrackLayoutTemplate
}

// Apply mods to the SimulationTrackLayoutAliasTemplate
func (o *SimulationTrackLayoutAliasTemplate) Apply(ctx context.Context, mods ...SimulationTrackLayoutAliasMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.SimulationTrackLayoutAlias
// according to the relationships in the template. Nothing is inserted into the db
func (t SimulationTrackLayoutAliasTemplate) setModelRels(o *models.SimulationTrackLayoutAlias) {
	if t.r.SimulationRacingSim != nil {
		rel := t.r.SimulationRacingSim.o.Build()
		rel.R.SimulationSimulationTrackLayoutAliases = append(rel.R.SimulationSimulationTrackLayoutAliases, o)
		o.SimulationID = rel.ID // h2
		o.R.SimulationRacingSim = rel
	}

	if t.r.TrackLayout != nil {
		rel := t.r.TrackLayout.o.Build()
		rel.R.SimulationTrackLayoutAliases = append(rel.R.SimulationTrackLayoutAliases, o)
		o.TrackLayoutID = rel.ID // h2
		o.R.TrackLayout = rel
	}
}

// BuildSetter returns an *models.SimulationTrackLayoutAliasSetter
// this does nothing with the relationship templates
func (o SimulationTrackLayoutAliasTemplate) BuildSetter() *models.SimulationTrackLayoutAliasSetter {
	m := &models.SimulationTrackLayoutAliasSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.TrackLayoutID != nil {
		val := o.TrackLayoutID()
		m.TrackLayoutID = omit.From(val)
	}
	if o.SimulationID != nil {
		val := o.SimulationID()
		m.SimulationID = omit.From(val)
	}
	if o.ExternalName != nil {
		val := o.ExternalName()
		m.ExternalName = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}
	if o.CreatedBy != nil {
		val := o.CreatedBy()
		m.CreatedBy = omit.From(val)
	}
	if o.UpdatedBy != nil {
		val := o.UpdatedBy()
		m.UpdatedBy = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.SimulationTrackLayoutAliasSetter
// this does nothing with the relationship templates
func (o SimulationTrackLayoutAliasTemplate) BuildManySetter(number int) []*models.SimulationTrackLayoutAliasSetter {
	m := make([]*models.SimulationTrackLayoutAliasSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.SimulationTrackLayoutAlias
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SimulationTrackLayoutAliasTemplate.Create
func (o SimulationTrackLayoutAliasTemplate) Build() *models.SimulationTrackLayoutAlias {
	m := &models.SimulationTrackLayoutAlias{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.TrackLayoutID != nil {
		m.TrackLayoutID = o.TrackLayoutID()
	}
	if o.SimulationID != nil {
		m.SimulationID = o.SimulationID()
	}
	if o.ExternalName != nil {
		m.ExternalName = o.ExternalName()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.CreatedBy != nil {
		m.CreatedBy = o.CreatedBy()
	}
	if o.UpdatedBy != nil {
		m.UpdatedBy = o.UpdatedBy()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.SimulationTrackLayoutAliasSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SimulationTrackLayoutAliasTemplate.CreateMany
func (o SimulationTrackLayoutAliasTemplate) BuildMany(number int) models.SimulationTrackLayoutAliasSlice {
	m := make(models.SimulationTrackLayoutAliasSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableSimulationTrackLayoutAlias(m *models.SimulationTrackLayoutAliasSetter) {
	if !(m.TrackLayoutID.IsValue()) {
		val := random_int32(nil)
		m.TrackLayoutID = omit.From(val)
	}
	if !(m.SimulationID.IsValue()) {
		val := random_int32(nil)
		m.SimulationID = omit.From(val)
	}
	if !(m.ExternalName.IsValue()) {
		val := random_string(nil)
		m.ExternalName = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.SimulationTrackLayoutAlias
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *SimulationTrackLayoutAliasTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.SimulationTrackLayoutAlias) error {
	var err error

	return err
}

// Create builds a simulationTrackLayoutAlias and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *SimulationTrackLayoutAliasTemplate) Create(ctx context.Context, exec bob.Executor) (*models.SimulationTrackLayoutAlias, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableSimulationTrackLayoutAlias(opt)

	if o.r.SimulationRacingSim == nil {
		SimulationTrackLayoutAliasMods.WithNewSimulationRacingSim().Apply(ctx, o)
	}

	var rel0 *models.RacingSim

	if o.r.SimulationRacingSim.o.alreadyPersisted {
		rel0 = o.r.SimulationRacingSim.o.Build()
	} else {
		rel0, err = o.r.SimulationRacingSim.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.SimulationID = omit.From(rel0.ID)

	if o.r.TrackLayout == nil {
		SimulationTrackLayoutAliasMods.WithNewTrackLayout().Apply(ctx, o)
	}

	var rel1 *models.TrackLayout

	if o.r.TrackLayout.o.alreadyPersisted {
		rel1 = o.r.TrackLayout.o.Build()
	} else {
		rel1, err = o.r.TrackLayout.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.TrackLayoutID = omit.From(rel1.ID)

	m, err := models.SimulationTrackLayoutAliases.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.SimulationRacingSim = rel0
	m.R.TrackLayout = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a simulationTrackLayoutAlias and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *SimulationTrackLayoutAliasTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.SimulationTrackLayoutAlias {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a simulationTrackLayoutAlias and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *SimulationTrackLayoutAliasTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.SimulationTrackLayoutAlias {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple simulationTrackLayoutAliases and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o SimulationTrackLayoutAliasTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.SimulationTrackLayoutAliasSlice, error) {
	var err error
	m := make(models.SimulationTrackLayoutAliasSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple simulationTrackLayoutAliases and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o SimulationTrackLayoutAliasTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.SimulationTrackLayoutAliasSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple simulationTrackLayoutAliases and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o SimulationTrackLayoutAliasTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.SimulationTrackLayoutAliasSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// SimulationTrackLayoutAlias has methods that act as mods for the SimulationTrackLayoutAliasTemplate
var SimulationTrackLayoutAliasMods simulationTrackLayoutAliasMods

type simulationTrackLayoutAliasMods struct{}

func (m simulationTrackLayoutAliasMods) RandomizeAllColumns(f *faker.Faker) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModSlice{
		SimulationTrackLayoutAliasMods.RandomID(f),
		SimulationTrackLayoutAliasMods.RandomTrackLayoutID(f),
		SimulationTrackLayoutAliasMods.RandomSimulationID(f),
		SimulationTrackLayoutAliasMods.RandomExternalName(f),
		SimulationTrackLayoutAliasMods.RandomCreatedAt(f),
		SimulationTrackLayoutAliasMods.RandomUpdatedAt(f),
		SimulationTrackLayoutAliasMods.RandomCreatedBy(f),
		SimulationTrackLayoutAliasMods.RandomUpdatedBy(f),
	}
}

// Set the model columns to this value
func (m simulationTrackLayoutAliasMods) ID(val int32) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m simulationTrackLayoutAliasMods) IDFunc(f func() int32) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m simulationTrackLayoutAliasMods) UnsetID() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m simulationTrackLayoutAliasMods) RandomID(f *faker.Faker) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m simulationTrackLayoutAliasMods) TrackLayoutID(val int32) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.TrackLayoutID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m simulationTrackLayoutAliasMods) TrackLayoutIDFunc(f func() int32) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.TrackLayoutID = f
	})
}

// Clear any values for the column
func (m simulationTrackLayoutAliasMods) UnsetTrackLayoutID() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.TrackLayoutID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m simulationTrackLayoutAliasMods) RandomTrackLayoutID(f *faker.Faker) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.TrackLayoutID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m simulationTrackLayoutAliasMods) SimulationID(val int32) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.SimulationID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m simulationTrackLayoutAliasMods) SimulationIDFunc(f func() int32) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.SimulationID = f
	})
}

// Clear any values for the column
func (m simulationTrackLayoutAliasMods) UnsetSimulationID() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.SimulationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m simulationTrackLayoutAliasMods) RandomSimulationID(f *faker.Faker) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.SimulationID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m simulationTrackLayoutAliasMods) ExternalName(val string) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.ExternalName = func() string { return val }
	})
}

// Set the Column from the function
func (m simulationTrackLayoutAliasMods) ExternalNameFunc(f func() string) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.ExternalName = f
	})
}

// Clear any values for the column
func (m simulationTrackLayoutAliasMods) UnsetExternalName() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.ExternalName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m simulationTrackLayoutAliasMods) RandomExternalName(f *faker.Faker) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.ExternalName = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m simulationTrackLayoutAliasMods) CreatedAt(val time.Time) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m simulationTrackLayoutAliasMods) CreatedAtFunc(f func() time.Time) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m simulationTrackLayoutAliasMods) UnsetCreatedAt() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m simulationTrackLayoutAliasMods) RandomCreatedAt(f *faker.Faker) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m simulationTrackLayoutAliasMods) UpdatedAt(val time.Time) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m simulationTrackLayoutAliasMods) UpdatedAtFunc(f func() time.Time) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m simulationTrackLayoutAliasMods) UnsetUpdatedAt() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m simulationTrackLayoutAliasMods) RandomUpdatedAt(f *faker.Faker) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m simulationTrackLayoutAliasMods) CreatedBy(val string) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.CreatedBy = func() string { return val }
	})
}

// Set the Column from the function
func (m simulationTrackLayoutAliasMods) CreatedByFunc(f func() string) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.CreatedBy = f
	})
}

// Clear any values for the column
func (m simulationTrackLayoutAliasMods) UnsetCreatedBy() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.CreatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m simulationTrackLayoutAliasMods) RandomCreatedBy(f *faker.Faker) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.CreatedBy = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m simulationTrackLayoutAliasMods) UpdatedBy(val string) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.UpdatedBy = func() string { return val }
	})
}

// Set the Column from the function
func (m simulationTrackLayoutAliasMods) UpdatedByFunc(f func() string) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.UpdatedBy = f
	})
}

// Clear any values for the column
func (m simulationTrackLayoutAliasMods) UnsetUpdatedBy() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.UpdatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m simulationTrackLayoutAliasMods) RandomUpdatedBy(f *faker.Faker) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(_ context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.UpdatedBy = func() string {
			return random_string(f)
		}
	})
}

func (m simulationTrackLayoutAliasMods) WithParentsCascading() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(ctx context.Context, o *SimulationTrackLayoutAliasTemplate) {
		if isDone, _ := simulationTrackLayoutAliasWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = simulationTrackLayoutAliasWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewRacingSimWithContext(ctx, RacingSimMods.WithParentsCascading())
			m.WithSimulationRacingSim(related).Apply(ctx, o)
		}
		{

			related := o.f.NewTrackLayoutWithContext(ctx, TrackLayoutMods.WithParentsCascading())
			m.WithTrackLayout(related).Apply(ctx, o)
		}
	})
}

func (m simulationTrackLayoutAliasMods) WithSimulationRacingSim(rel *RacingSimTemplate) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(ctx context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.r.SimulationRacingSim = &simulationTrackLayoutAliasRSimulationRacingSimR{
			o: rel,
		}
	})
}

func (m simulationTrackLayoutAliasMods) WithNewSimulationRacingSim(mods ...RacingSimMod) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(ctx context.Context, o *SimulationTrackLayoutAliasTemplate) {
		related := o.f.NewRacingSimWithContext(ctx, mods...)

		m.WithSimulationRacingSim(related).Apply(ctx, o)
	})
}

func (m simulationTrackLayoutAliasMods) WithExistingSimulationRacingSim(em *models.RacingSim) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(ctx context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.r.SimulationRacingSim = &simulationTrackLayoutAliasRSimulationRacingSimR{
			o: o.f.FromExistingRacingSim(em),
		}
	})
}

func (m simulationTrackLayoutAliasMods) WithoutSimulationRacingSim() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(ctx context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.r.SimulationRacingSim = nil
	})
}

func (m simulationTrackLayoutAliasMods) WithTrackLayout(rel *TrackLayoutTemplate) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(ctx context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.r.TrackLayout = &simulationTrackLayoutAliasRTrackLayoutR{
			o: rel,
		}
	})
}

func (m simulationTrackLayoutAliasMods) WithNewTrackLayout(mods ...TrackLayoutMod) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(ctx context.Context, o *SimulationTrackLayoutAliasTemplate) {
		related := o.f.NewTrackLayoutWithContext(ctx, mods...)

		m.WithTrackLayout(related).Apply(ctx, o)
	})
}

func (m simulationTrackLayoutAliasMods) WithExistingTrackLayout(em *models.TrackLayout) SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(ctx context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.r.TrackLayout = &simulationTrackLayoutAliasRTrackLayoutR{
			o: o.f.FromExistingTrackLayout(em),
		}
	})
}

func (m simulationTrackLayoutAliasMods) WithoutTrackLayout() SimulationTrackLayoutAliasMod {
	return SimulationTrackLayoutAliasModFunc(func(ctx context.Context, o *SimulationTrackLayoutAliasTemplate) {
		o.r.TrackLayout = nil
	})
}
