// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var CarClasses = Table[
	carClassColumns,
	carClassIndexes,
	carClassForeignKeys,
	carClassUniques,
	carClassChecks,
]{
	Schema: "",
	Name:   "car_classes",
	Columns: carClassColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('car_classes_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsActive: column{
			Name:      "is_active",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedBy: column{
			Name:      "created_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedBy: column{
			Name:      "updated_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: carClassIndexes{
		CarClassesPkey: index{
			Type: "btree",
			Name: "car_classes_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		CarClassesNameUnique: index{
			Type: "btree",
			Name: "car_classes_name_unique",
			Columns: []indexColumn{
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxCarClassesIsActive: index{
			Type: "btree",
			Name: "idx_car_classes_is_active",
			Columns: []indexColumn{
				{
					Name:         "is_active",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "car_classes_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: carClassUniques{
		CarClassesNameUnique: constraint{
			Name:    "car_classes_name_unique",
			Columns: []string{"name"},
			Comment: "",
		},
	},

	Comment: "",
}

type carClassColumns struct {
	ID        column
	Name      column
	IsActive  column
	CreatedAt column
	UpdatedAt column
	CreatedBy column
	UpdatedBy column
}

func (c carClassColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.IsActive, c.CreatedAt, c.UpdatedAt, c.CreatedBy, c.UpdatedBy,
	}
}

type carClassIndexes struct {
	CarClassesPkey        index
	CarClassesNameUnique  index
	IdxCarClassesIsActive index
}

func (i carClassIndexes) AsSlice() []index {
	return []index{
		i.CarClassesPkey, i.CarClassesNameUnique, i.IdxCarClassesIsActive,
	}
}

type carClassForeignKeys struct{}

func (f carClassForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type carClassUniques struct {
	CarClassesNameUnique constraint
}

func (u carClassUniques) AsSlice() []constraint {
	return []constraint{
		u.CarClassesNameUnique,
	}
}

type carClassChecks struct{}

func (c carClassChecks) AsSlice() []check {
	return []check{}
}
