// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var CarModels = Table[
	carModelColumns,
	carModelIndexes,
	carModelForeignKeys,
	carModelUniques,
	carModelChecks,
]{
	Schema: "",
	Name:   "car_models",
	Columns: carModelColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('car_models_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		BrandID: column{
			Name:      "brand_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsActive: column{
			Name:      "is_active",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedBy: column{
			Name:      "created_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedBy: column{
			Name:      "updated_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: carModelIndexes{
		CarModelsPkey: index{
			Type: "btree",
			Name: "car_models_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		CarModelsBrandIDNameUnique: index{
			Type: "btree",
			Name: "car_models_brand_id_name_unique",
			Columns: []indexColumn{
				{
					Name:         "brand_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxCarModelsBrandID: index{
			Type: "btree",
			Name: "idx_car_models_brand_id",
			Columns: []indexColumn{
				{
					Name:         "brand_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxCarModelsIsActive: index{
			Type: "btree",
			Name: "idx_car_models_is_active",
			Columns: []indexColumn{
				{
					Name:         "is_active",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "car_models_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: carModelForeignKeys{
		CarModelsCarModelsBrandIDFK: foreignKey{
			constraint: constraint{
				Name:    "car_models.car_models_brand_id_fk",
				Columns: []string{"brand_id"},
				Comment: "",
			},
			ForeignTable:   "car_brands",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: carModelUniques{
		CarModelsBrandIDNameUnique: constraint{
			Name:    "car_models_brand_id_name_unique",
			Columns: []string{"brand_id", "name"},
			Comment: "",
		},
	},

	Comment: "",
}

type carModelColumns struct {
	ID        column
	BrandID   column
	Name      column
	IsActive  column
	CreatedAt column
	UpdatedAt column
	CreatedBy column
	UpdatedBy column
}

func (c carModelColumns) AsSlice() []column {
	return []column{
		c.ID, c.BrandID, c.Name, c.IsActive, c.CreatedAt, c.UpdatedAt, c.CreatedBy, c.UpdatedBy,
	}
}

type carModelIndexes struct {
	CarModelsPkey              index
	CarModelsBrandIDNameUnique index
	IdxCarModelsBrandID        index
	IdxCarModelsIsActive       index
}

func (i carModelIndexes) AsSlice() []index {
	return []index{
		i.CarModelsPkey, i.CarModelsBrandIDNameUnique, i.IdxCarModelsBrandID, i.IdxCarModelsIsActive,
	}
}

type carModelForeignKeys struct {
	CarModelsCarModelsBrandIDFK foreignKey
}

func (f carModelForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.CarModelsCarModelsBrandIDFK,
	}
}

type carModelUniques struct {
	CarModelsBrandIDNameUnique constraint
}

func (u carModelUniques) AsSlice() []constraint {
	return []constraint{
		u.CarModelsBrandIDNameUnique,
	}
}

type carModelChecks struct{}

func (c carModelChecks) AsSlice() []check {
	return []check{}
}
