// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var RacingSims = Table[
	racingSimColumns,
	racingSimIndexes,
	racingSimForeignKeys,
	racingSimUniques,
	racingSimChecks,
]{
	Schema: "",
	Name:   "racing_sims",
	Columns: racingSimColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('racing_sims_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SupportedImportFormats: column{
			Name:      "supported_import_formats",
			DBType:    "text[]",
			Default:   "'{}'::text[]",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DataMapping: column{
			Name:      "data_mapping",
			DBType:    "jsonb",
			Default:   "'{}'::jsonb",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsActive: column{
			Name:      "is_active",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedBy: column{
			Name:      "created_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedBy: column{
			Name:      "updated_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: racingSimIndexes{
		RacingSimsPkey: index{
			Type: "btree",
			Name: "racing_sims_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxRacingSimsIsActive: index{
			Type: "btree",
			Name: "idx_racing_sims_is_active",
			Columns: []indexColumn{
				{
					Name:         "is_active",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		RacingSimsNameUnique: index{
			Type: "btree",
			Name: "racing_sims_name_unique",
			Columns: []indexColumn{
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "racing_sims_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: racingSimUniques{
		RacingSimsNameUnique: constraint{
			Name:    "racing_sims_name_unique",
			Columns: []string{"name"},
			Comment: "",
		},
	},

	Comment: "",
}

type racingSimColumns struct {
	ID                     column
	Name                   column
	SupportedImportFormats column
	DataMapping            column
	IsActive               column
	CreatedAt              column
	UpdatedAt              column
	CreatedBy              column
	UpdatedBy              column
}

func (c racingSimColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.SupportedImportFormats, c.DataMapping, c.IsActive, c.CreatedAt, c.UpdatedAt, c.CreatedBy, c.UpdatedBy,
	}
}

type racingSimIndexes struct {
	RacingSimsPkey        index
	IdxRacingSimsIsActive index
	RacingSimsNameUnique  index
}

func (i racingSimIndexes) AsSlice() []index {
	return []index{
		i.RacingSimsPkey, i.IdxRacingSimsIsActive, i.RacingSimsNameUnique,
	}
}

type racingSimForeignKeys struct{}

func (f racingSimForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type racingSimUniques struct {
	RacingSimsNameUnique constraint
}

func (u racingSimUniques) AsSlice() []constraint {
	return []constraint{
		u.RacingSimsNameUnique,
	}
}

type racingSimChecks struct{}

func (c racingSimChecks) AsSlice() []check {
	return []check{}
}
