// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var SeasonTeamStandings = Table[
	seasonTeamStandingColumns,
	seasonTeamStandingIndexes,
	seasonTeamStandingForeignKeys,
	seasonTeamStandingUniques,
	seasonTeamStandingChecks,
]{
	Schema: "",
	Name:   "season_team_standings",
	Columns: seasonTeamStandingColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('season_team_standings_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		FrontendID: column{
			Name:      "frontend_id",
			DBType:    "uuid",
			Default:   "uuid_generate_v4()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SeasonID: column{
			Name:      "season_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TeamID: column{
			Name:      "team_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Position: column{
			Name:      "position",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TotalPoints: column{
			Name:      "total_points",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DroppedEventIds: column{
			Name:      "dropped_event_ids",
			DBType:    "integer[]",
			Default:   "'{}'::integer[]",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LastRebuiltAt: column{
			Name:      "last_rebuilt_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedBy: column{
			Name:      "created_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedBy: column{
			Name:      "updated_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: seasonTeamStandingIndexes{
		SeasonTeamStandingsPkey: index{
			Type: "btree",
			Name: "season_team_standings_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxSeasonTeamStandingsSeasonIDPosition: index{
			Type: "btree",
			Name: "idx_season_team_standings_season_id_position",
			Columns: []indexColumn{
				{
					Name:         "season_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "\"position\"",
					Desc:         null.FromCond(false, true),
					IsExpression: true,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		SeasonTeamStandingsFrontendIDUnique: index{
			Type: "btree",
			Name: "season_team_standings_frontend_id_unique",
			Columns: []indexColumn{
				{
					Name:         "frontend_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		SeasonTeamStandingsSeasonIDTeamIDUnique: index{
			Type: "btree",
			Name: "season_team_standings_season_id_team_id_unique",
			Columns: []indexColumn{
				{
					Name:         "season_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "team_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "season_team_standings_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: seasonTeamStandingForeignKeys{
		SeasonTeamStandingsSeasonTeamStandingsSeasonIDFK: foreignKey{
			constraint: constraint{
				Name:    "season_team_standings.season_team_standings_season_id_fk",
				Columns: []string{"season_id"},
				Comment: "",
			},
			ForeignTable:   "seasons",
			ForeignColumns: []string{"id"},
		},
		SeasonTeamStandingsSeasonTeamStandingsTeamIDFK: foreignKey{
			constraint: constraint{
				Name:    "season_team_standings.season_team_standings_team_id_fk",
				Columns: []string{"team_id"},
				Comment: "",
			},
			ForeignTable:   "teams",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: seasonTeamStandingUniques{
		SeasonTeamStandingsFrontendIDUnique: constraint{
			Name:    "season_team_standings_frontend_id_unique",
			Columns: []string{"frontend_id"},
			Comment: "",
		},
		SeasonTeamStandingsSeasonIDTeamIDUnique: constraint{
			Name:    "season_team_standings_season_id_team_id_unique",
			Columns: []string{"season_id", "team_id"},
			Comment: "",
		},
	},

	Comment: "",
}

type seasonTeamStandingColumns struct {
	ID              column
	FrontendID      column
	SeasonID        column
	TeamID          column
	Position        column
	TotalPoints     column
	DroppedEventIds column
	LastRebuiltAt   column
	CreatedAt       column
	UpdatedAt       column
	CreatedBy       column
	UpdatedBy       column
}

func (c seasonTeamStandingColumns) AsSlice() []column {
	return []column{
		c.ID, c.FrontendID, c.SeasonID, c.TeamID, c.Position, c.TotalPoints, c.DroppedEventIds, c.LastRebuiltAt, c.CreatedAt, c.UpdatedAt, c.CreatedBy, c.UpdatedBy,
	}
}

type seasonTeamStandingIndexes struct {
	SeasonTeamStandingsPkey                 index
	IdxSeasonTeamStandingsSeasonIDPosition  index
	SeasonTeamStandingsFrontendIDUnique     index
	SeasonTeamStandingsSeasonIDTeamIDUnique index
}

func (i seasonTeamStandingIndexes) AsSlice() []index {
	return []index{
		i.SeasonTeamStandingsPkey, i.IdxSeasonTeamStandingsSeasonIDPosition, i.SeasonTeamStandingsFrontendIDUnique, i.SeasonTeamStandingsSeasonIDTeamIDUnique,
	}
}

type seasonTeamStandingForeignKeys struct {
	SeasonTeamStandingsSeasonTeamStandingsSeasonIDFK foreignKey
	SeasonTeamStandingsSeasonTeamStandingsTeamIDFK   foreignKey
}

func (f seasonTeamStandingForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.SeasonTeamStandingsSeasonTeamStandingsSeasonIDFK, f.SeasonTeamStandingsSeasonTeamStandingsTeamIDFK,
	}
}

type seasonTeamStandingUniques struct {
	SeasonTeamStandingsFrontendIDUnique     constraint
	SeasonTeamStandingsSeasonIDTeamIDUnique constraint
}

func (u seasonTeamStandingUniques) AsSlice() []constraint {
	return []constraint{
		u.SeasonTeamStandingsFrontendIDUnique, u.SeasonTeamStandingsSeasonIDTeamIDUnique,
	}
}

type seasonTeamStandingChecks struct{}

func (c seasonTeamStandingChecks) AsSlice() []check {
	return []check{}
}
