// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var TrackLayouts = Table[
	trackLayoutColumns,
	trackLayoutIndexes,
	trackLayoutForeignKeys,
	trackLayoutUniques,
	trackLayoutChecks,
]{
	Schema: "",
	Name:   "track_layouts",
	Columns: trackLayoutColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('track_layouts_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TrackID: column{
			Name:      "track_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LengthMeters: column{
			Name:      "length_meters",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		LayoutImageURL: column{
			Name:      "layout_image_url",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		IsActive: column{
			Name:      "is_active",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedBy: column{
			Name:      "created_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedBy: column{
			Name:      "updated_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: trackLayoutIndexes{
		TrackLayoutsPkey: index{
			Type: "btree",
			Name: "track_layouts_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxTrackLayoutsIsActive: index{
			Type: "btree",
			Name: "idx_track_layouts_is_active",
			Columns: []indexColumn{
				{
					Name:         "is_active",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxTrackLayoutsTrackID: index{
			Type: "btree",
			Name: "idx_track_layouts_track_id",
			Columns: []indexColumn{
				{
					Name:         "track_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		TrackLayoutsTrackIDNameUnique: index{
			Type: "btree",
			Name: "track_layouts_track_id_name_unique",
			Columns: []indexColumn{
				{
					Name:         "track_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "track_layouts_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: trackLayoutForeignKeys{
		TrackLayoutsTrackLayoutsTrackIDFK: foreignKey{
			constraint: constraint{
				Name:    "track_layouts.track_layouts_track_id_fk",
				Columns: []string{"track_id"},
				Comment: "",
			},
			ForeignTable:   "tracks",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: trackLayoutUniques{
		TrackLayoutsTrackIDNameUnique: constraint{
			Name:    "track_layouts_track_id_name_unique",
			Columns: []string{"track_id", "name"},
			Comment: "",
		},
	},
	Checks: trackLayoutChecks{
		TrackLayoutsLengthMetersCheck: check{
			constraint: constraint{
				Name:    "track_layouts_length_meters_check",
				Columns: []string{"length_meters"},
				Comment: "",
			},
			Expression: "((length_meters IS NULL) OR (length_meters > 0))",
		},
	},
	Comment: "",
}

type trackLayoutColumns struct {
	ID             column
	TrackID        column
	Name           column
	LengthMeters   column
	LayoutImageURL column
	IsActive       column
	CreatedAt      column
	UpdatedAt      column
	CreatedBy      column
	UpdatedBy      column
}

func (c trackLayoutColumns) AsSlice() []column {
	return []column{
		c.ID, c.TrackID, c.Name, c.LengthMeters, c.LayoutImageURL, c.IsActive, c.CreatedAt, c.UpdatedAt, c.CreatedBy, c.UpdatedBy,
	}
}

type trackLayoutIndexes struct {
	TrackLayoutsPkey              index
	IdxTrackLayoutsIsActive       index
	IdxTrackLayoutsTrackID        index
	TrackLayoutsTrackIDNameUnique index
}

func (i trackLayoutIndexes) AsSlice() []index {
	return []index{
		i.TrackLayoutsPkey, i.IdxTrackLayoutsIsActive, i.IdxTrackLayoutsTrackID, i.TrackLayoutsTrackIDNameUnique,
	}
}

type trackLayoutForeignKeys struct {
	TrackLayoutsTrackLayoutsTrackIDFK foreignKey
}

func (f trackLayoutForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.TrackLayoutsTrackLayoutsTrackIDFK,
	}
}

type trackLayoutUniques struct {
	TrackLayoutsTrackIDNameUnique constraint
}

func (u trackLayoutUniques) AsSlice() []constraint {
	return []constraint{
		u.TrackLayoutsTrackIDNameUnique,
	}
}

type trackLayoutChecks struct {
	TrackLayoutsLengthMetersCheck check
}

func (c trackLayoutChecks) AsSlice() []check {
	return []check{
		c.TrackLayoutsLengthMetersCheck,
	}
}
