// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Tracks = Table[
	trackColumns,
	trackIndexes,
	trackForeignKeys,
	trackUniques,
	trackChecks,
]{
	Schema: "",
	Name:   "tracks",
	Columns: trackColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('tracks_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Country: column{
			Name:      "country",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Latitude: column{
			Name:      "latitude",
			DBType:    "numeric",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Longitude: column{
			Name:      "longitude",
			DBType:    "numeric",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		WebsiteURL: column{
			Name:      "website_url",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		IsActive: column{
			Name:      "is_active",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedBy: column{
			Name:      "created_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedBy: column{
			Name:      "updated_by",
			DBType:    "text",
			Default:   "'system'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: trackIndexes{
		TracksPkey: index{
			Type: "btree",
			Name: "tracks_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxTracksIsActive: index{
			Type: "btree",
			Name: "idx_tracks_is_active",
			Columns: []indexColumn{
				{
					Name:         "is_active",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		TracksNameUnique: index{
			Type: "btree",
			Name: "tracks_name_unique",
			Columns: []indexColumn{
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "tracks_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: trackUniques{
		TracksNameUnique: constraint{
			Name:    "tracks_name_unique",
			Columns: []string{"name"},
			Comment: "",
		},
	},

	Comment: "",
}

type trackColumns struct {
	ID         column
	Name       column
	Country    column
	Latitude   column
	Longitude  column
	WebsiteURL column
	IsActive   column
	CreatedAt  column
	UpdatedAt  column
	CreatedBy  column
	UpdatedBy  column
}

func (c trackColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Country, c.Latitude, c.Longitude, c.WebsiteURL, c.IsActive, c.CreatedAt, c.UpdatedAt, c.CreatedBy, c.UpdatedBy,
	}
}

type trackIndexes struct {
	TracksPkey        index
	IdxTracksIsActive index
	TracksNameUnique  index
}

func (i trackIndexes) AsSlice() []index {
	return []index{
		i.TracksPkey, i.IdxTracksIsActive, i.TracksNameUnique,
	}
}

type trackForeignKeys struct{}

func (f trackForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type trackUniques struct {
	TracksNameUnique constraint
}

func (u trackUniques) AsSlice() []constraint {
	return []constraint{
		u.TracksNameUnique,
	}
}

type trackChecks struct{}

func (c trackChecks) AsSlice() []check {
	return []check{}
}
