// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var DriverErrors = &driverErrors{
	ErrUniqueDriversPkey: &UniqueConstraintError{
		schema:  "",
		table:   "drivers",
		columns: []string{"id"},
		s:       "drivers_pkey",
	},

	ErrUniqueDriversExternalIdUnique: &UniqueConstraintError{
		schema:  "",
		table:   "drivers",
		columns: []string{"external_id"},
		s:       "drivers_external_id_unique",
	},
}

type driverErrors struct {
	ErrUniqueDriversPkey *UniqueConstraintError

	ErrUniqueDriversExternalIdUnique *UniqueConstraintError
}
