// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var PointRuleErrors = &pointRuleErrors{
	ErrUniquePointRulesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "point_rules",
		columns: []string{"id"},
		s:       "point_rules_pkey",
	},
}

type pointRuleErrors struct {
	ErrUniquePointRulesPkey *UniqueConstraintError
}
