// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SeasonDriverStandingErrors = &seasonDriverStandingErrors{
	ErrUniqueSeasonDriverStandingsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "season_driver_standings",
		columns: []string{"id"},
		s:       "season_driver_standings_pkey",
	},

	ErrUniqueSeasonDriverStandingsFrontendIdUnique: &UniqueConstraintError{
		schema:  "",
		table:   "season_driver_standings",
		columns: []string{"frontend_id"},
		s:       "season_driver_standings_frontend_id_unique",
	},

	ErrUniqueSeasonDriverStandingsSeasonIdDriverIdUnique: &UniqueConstraintError{
		schema:  "",
		table:   "season_driver_standings",
		columns: []string{"season_id", "driver_id"},
		s:       "season_driver_standings_season_id_driver_id_unique",
	},
}

type seasonDriverStandingErrors struct {
	ErrUniqueSeasonDriverStandingsPkey *UniqueConstraintError

	ErrUniqueSeasonDriverStandingsFrontendIdUnique *UniqueConstraintError

	ErrUniqueSeasonDriverStandingsSeasonIdDriverIdUnique *UniqueConstraintError
}
