// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SeriesErrors = &seriesErrors{
	ErrUniqueSeriesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "series",
		columns: []string{"id"},
		s:       "series_pkey",
	},

	ErrUniqueSeriesNameUnique: &UniqueConstraintError{
		schema:  "",
		table:   "series",
		columns: []string{"name"},
		s:       "series_name_unique",
	},
}

type seriesErrors struct {
	ErrUniqueSeriesPkey *UniqueConstraintError

	ErrUniqueSeriesNameUnique *UniqueConstraintError
}
