// Code generated by BobGen psql v0.43.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

import (
	"context"
	"errors"
	"testing"

	factory "github.com/srlmgr/backend/db/factory"
	models "github.com/srlmgr/backend/db/models"
	"github.com/stephenafamo/bob"
)

func TestSimulationDriverAliasUniqueConstraintErrors(t *testing.T) {
	if testDB == nil {
		t.Skip("No database connection provided")
	}

	f := factory.New()
	tests := []struct {
		name         string
		expectedErr  *UniqueConstraintError
		conflictMods func(context.Context, *testing.T, bob.Executor, *models.SimulationDriverAlias) factory.SimulationDriverAliasModSlice
	}{
		{
			name:        "ErrUniqueSimulationDriverAliasesPkey",
			expectedErr: SimulationDriverAliasErrors.ErrUniqueSimulationDriverAliasesPkey,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.SimulationDriverAlias) factory.SimulationDriverAliasModSlice {
				shouldUpdate := false
				updateMods := make(factory.SimulationDriverAliasModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewSimulationDriverAliasWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.SimulationDriverAliasModSlice{
					factory.SimulationDriverAliasMods.ID(obj.ID),
				}
			},
		},
		{
			name:        "ErrUniqueSimulationDriverAliasesDriverIdSimulationIdUnique",
			expectedErr: SimulationDriverAliasErrors.ErrUniqueSimulationDriverAliasesDriverIdSimulationIdUnique,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.SimulationDriverAlias) factory.SimulationDriverAliasModSlice {
				shouldUpdate := false
				updateMods := make(factory.SimulationDriverAliasModSlice, 0, 2)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewSimulationDriverAliasWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.SimulationDriverAliasModSlice{
					factory.SimulationDriverAliasMods.DriverID(obj.DriverID),
					factory.SimulationDriverAliasMods.SimulationID(obj.SimulationID),
				}
			},
		},
		{
			name:        "ErrUniqueSimulationDriverAliasesSimulationIdDriverKeyUnique",
			expectedErr: SimulationDriverAliasErrors.ErrUniqueSimulationDriverAliasesSimulationIdDriverKeyUnique,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.SimulationDriverAlias) factory.SimulationDriverAliasModSlice {
				shouldUpdate := false
				updateMods := make(factory.SimulationDriverAliasModSlice, 0, 2)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewSimulationDriverAliasWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.SimulationDriverAliasModSlice{
					factory.SimulationDriverAliasMods.SimulationID(obj.SimulationID),
					factory.SimulationDriverAliasMods.SimulationDriverID(obj.SimulationDriverID),
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(t.Context())
			t.Cleanup(cancel)

			tx, err := testDB.Begin(ctx)
			if err != nil {
				t.Fatalf("Couldn't start database transaction: %v", err)
			}

			defer func() {
				if err := tx.Rollback(ctx); err != nil {
					t.Fatalf("Error rolling back transaction: %v", err)
				}
			}()

			var exec bob.Executor = tx

			obj, err := f.NewSimulationDriverAliasWithContext(ctx, factory.SimulationDriverAliasMods.WithParentsCascading()).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			obj2, err := f.NewSimulationDriverAliasWithContext(ctx).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			err = obj2.Update(ctx, exec, f.NewSimulationDriverAliasWithContext(ctx, tt.conflictMods(ctx, t, exec, obj)...).BuildSetter())
			if !errors.Is(ErrUniqueConstraint, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !errors.Is(tt.expectedErr, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
			if !ErrUniqueConstraint.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !tt.expectedErr.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
		})
	}
}
