// Code generated by BobGen psql v0.46.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SimulationDriverAliasErrors = &simulationDriverAliasErrors{
	ErrUniqueSimulationDriverAliasesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "simulation_driver_aliases",
		columns: []string{"id"},
		s:       "simulation_driver_aliases_pkey",
	},

	ErrUniqueSimulationDriverAliasesSimulationIdDriverKeyUnique: &UniqueConstraintError{
		schema:  "",
		table:   "simulation_driver_aliases",
		columns: []string{"simulation_id", "simulation_driver_id"},
		s:       "simulation_driver_aliases_simulation_id_driver_key_unique",
	},
}

type simulationDriverAliasErrors struct {
	ErrUniqueSimulationDriverAliasesPkey *UniqueConstraintError

	ErrUniqueSimulationDriverAliasesSimulationIdDriverKeyUnique *UniqueConstraintError
}
