// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SimulationCarAliasErrors = &simulationCarAliasErrors{
	ErrUniqueSimulationCarAliasesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "simulation_car_aliases",
		columns: []string{"id"},
		s:       "simulation_car_aliases_pkey",
	},

	ErrUniqueSimulationCarAliasesCarModelIdSimulationIdUnique: &UniqueConstraintError{
		schema:  "",
		table:   "simulation_car_aliases",
		columns: []string{"car_model_id", "simulation_id"},
		s:       "simulation_car_aliases_car_model_id_simulation_id_unique",
	},

	ErrUniqueSimulationCarAliasesSimulationIdExternalNameUnique: &UniqueConstraintError{
		schema:  "",
		table:   "simulation_car_aliases",
		columns: []string{"simulation_id", "external_name"},
		s:       "simulation_car_aliases_simulation_id_external_name_unique",
	},
}

type simulationCarAliasErrors struct {
	ErrUniqueSimulationCarAliasesPkey *UniqueConstraintError

	ErrUniqueSimulationCarAliasesCarModelIdSimulationIdUnique *UniqueConstraintError

	ErrUniqueSimulationCarAliasesSimulationIdExternalNameUnique *UniqueConstraintError
}
