name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]

jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.26.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: go mod download

      - name: Test
        # due to database tests we need to run tests sequentially, so we set -p 1 to disable parallel test execution
        # may be changed if we decide to split tests into multiple packages and run them in parallel
        run: go test ./... -p 1 -race -coverprofile=coverage.txt -covermode=atomic -gcflags=-l
